// draft_picks.js — Gridiron Oracle rookie baseline data
// AUTO-GENERATED by scripts/fetch_draft_picks.py — DO NOT EDIT MANUALLY
// Baseline seasons: 2015-2025
// Current draft class: 2026
// Generated: 2026-08-25T02:25:27.203232+00:00
//
// ROUND_BASELINES: historical average rookie-season PPR points by
// position and round, used to project rookies with no nfl_data.js
// history. Built from real outcomes, not assumptions — but note this
// is a rough baseline, not a player-specific projection. A "good"
// or "bad" rookie within the same draft slot will vary widely; this
// gives a reasonable starting point rather than pretending precision.

export const ROUND_BASELINES = {
  "QB": {
    "1": {
      "mean": 13.3,
      "median": 13.3,
      "count": 37
    },
    "2": {
      "mean": 8.4,
      "median": 11.3,
      "count": 7
    },
    "3": {
      "mean": 4.1,
      "median": 1.0,
      "count": 16
    },
    "4": {
      "mean": 3.6,
      "median": 0.0,
      "count": 15
    },
    "5": {
      "mean": 3.4,
      "median": 0.7,
      "count": 15
    },
    "6": {
      "mean": 2.6,
      "median": 0.0,
      "count": 20
    },
    "7": {
      "mean": 1.8,
      "median": 0.0,
      "count": 17
    }
  },
  "RB": {
    "1": {
      "mean": 14.0,
      "median": 14.6,
      "count": 16
    },
    "2": {
      "mean": 10.3,
      "median": 11.6,
      "count": 24
    },
    "3": {
      "mean": 7.2,
      "median": 6.3,
      "count": 32
    },
    "4": {
      "mean": 5.7,
      "median": 5.9,
      "count": 48
    },
    "5": {
      "mean": 4.1,
      "median": 3.7,
      "count": 37
    },
    "6": {
      "mean": 2.5,
      "median": 2.2,
      "count": 37
    },
    "7": {
      "mean": 2.2,
      "median": 0.5,
      "count": 39
    }
  },
  "WR": {
    "1": {
      "mean": 9.4,
      "median": 9.3,
      "count": 49
    },
    "2": {
      "mean": 7.6,
      "median": 7.5,
      "count": 53
    },
    "3": {
      "mean": 4.8,
      "median": 4.0,
      "count": 50
    },
    "4": {
      "mean": 3.3,
      "median": 2.3,
      "count": 48
    },
    "5": {
      "mean": 3.9,
      "median": 1.8,
      "count": 45
    },
    "6": {
      "mean": 2.0,
      "median": 1.1,
      "count": 59
    },
    "7": {
      "mean": 1.5,
      "median": 0.0,
      "count": 53
    }
  },
  "TE": {
    "1": {
      "mean": 9.1,
      "median": 9.7,
      "count": 11
    },
    "2": {
      "mean": 5.3,
      "median": 4.9,
      "count": 20
    },
    "3": {
      "mean": 3.3,
      "median": 2.3,
      "count": 27
    },
    "4": {
      "mean": 4.7,
      "median": 4.6,
      "count": 30
    },
    "5": {
      "mean": 2.9,
      "median": 2.7,
      "count": 29
    },
    "6": {
      "mean": 1.4,
      "median": 0.0,
      "count": 21
    },
    "7": {
      "mean": 0.8,
      "median": 0.0,
      "count": 22
    }
  }
};

// CURRENT_DRAFT_CLASS: gsis_id -> round, pick, position, name
export const CURRENT_DRAFT_CLASS = {
  "MEN516487": {
    "round": 1,
    "pick": 1,
    "position": "QB",
    "name": "Fernando Mendoza"
  },
  "LOV121782": {
    "round": 1,
    "pick": 3,
    "position": "RB",
    "name": "Jeremiyah Love"
  },
  "TAT143045": {
    "round": 1,
    "pick": 4,
    "position": "WR",
    "name": "Carnell Tate"
  },
  "TYS405541": {
    "round": 1,
    "pick": 8,
    "position": "WR",
    "name": "Jordyn Tyson"
  },
  "SIM639376": {
    "round": 1,
    "pick": 13,
    "position": "QB",
    "name": "Ty Simpson"
  },
  "SAD482340": {
    "round": 1,
    "pick": 16,
    "position": "TE",
    "name": "Kenyon Sadiq"
  },
  "LEM694125": {
    "round": 1,
    "pick": 20,
    "position": "WR",
    "name": "Makai Lemon"
  },
  "CON046719": {
    "round": 1,
    "pick": 24,
    "position": "WR",
    "name": "KC Concepcion"
  },
  "COO816508": {
    "round": 1,
    "pick": 30,
    "position": "WR",
    "name": "Omar Cooper Jr."
  },
  "PRI206342": {
    "round": 1,
    "pick": 32,
    "position": "RB",
    "name": "Jadarian Price"
  },
  "BOS677861": {
    "round": 2,
    "pick": 39,
    "position": "WR",
    "name": "Denzel Boston"
  },
  "BER218265": {
    "round": 2,
    "pick": 47,
    "position": "WR",
    "name": "Germie Bernard"
  },
  "STO806346": {
    "round": 2,
    "pick": 54,
    "position": "TE",
    "name": "Eli Stowers"
  },
  "BOE586077": {
    "round": 2,
    "pick": 56,
    "position": "TE",
    "name": "Nate Boerkircher"
  },
  "KLE258860": {
    "round": 2,
    "pick": 59,
    "position": "TE",
    "name": "Marlin Klein"
  },
  "KLA269938": {
    "round": 2,
    "pick": 61,
    "position": "TE",
    "name": "Max Klare"
  },
  "ROU550040": {
    "round": 3,
    "pick": 69,
    "position": "TE",
    "name": "Sam Roush"
  },
  "WIL143106": {
    "round": 3,
    "pick": 71,
    "position": "WR",
    "name": "Antonio Williams"
  },
  "FIE775129": {
    "round": 3,
    "pick": 74,
    "position": "WR",
    "name": "Malachi Fields"
  },
  "DOU210628": {
    "round": 3,
    "pick": 75,
    "position": "WR",
    "name": "Caleb Douglas"
  },
  "ALL015451": {
    "round": 3,
    "pick": 76,
    "position": "QB",
    "name": "Drew Allar"
  },
  "BRA531428": {
    "round": 3,
    "pick": 79,
    "position": "WR",
    "name": "Zachariah Branch"
  },
  "LAN311008": {
    "round": 3,
    "pick": 80,
    "position": "WR",
    "name": "Ja'Kobi Lane"
  },
  "BRA836631": {
    "round": 3,
    "pick": 83,
    "position": "WR",
    "name": "Chris Brazzell II"
  },
  "HUR541377": {
    "round": 3,
    "pick": 84,
    "position": "WR",
    "name": "Ted Hurst"
  },
  "KAC282861": {
    "round": 3,
    "pick": 87,
    "position": "TE",
    "name": "Will Kacmarek"
  },
  "THO417520": {
    "round": 3,
    "pick": 89,
    "position": "WR",
    "name": "Zavion Thomas"
  },
  "BLA097235": {
    "round": 3,
    "pick": 90,
    "position": "RB",
    "name": "Kaelon Black"
  },
  "BEL267684": {
    "round": 3,
    "pick": 94,
    "position": "WR",
    "name": "Chris Bell"
  },
  "RAR148318": {
    "round": 3,
    "pick": 95,
    "position": "TE",
    "name": "Eli Raridon"
  },
  "THO495568": {
    "round": 4,
    "pick": 105,
    "position": "WR",
    "name": "Brenen Thompson"
  },
  "COL293648": {
    "round": 4,
    "pick": 108,
    "position": "RB",
    "name": "Jonah Coleman"
  },
  "KLU066027": {
    "round": 4,
    "pick": 110,
    "position": "QB",
    "name": "Cade Klubnik"
  },
  "SAR527100": {
    "round": 4,
    "pick": 115,
    "position": "WR",
    "name": "Elijah Sarratt"
  },
  "WET055619": {
    "round": 4,
    "pick": 121,
    "position": "WR",
    "name": "Kaden Wetjen"
  },
  "WAS797326": {
    "round": 4,
    "pick": 122,
    "position": "RB",
    "name": "Mike Washington Jr."
  },
  "BEL597603": {
    "round": 4,
    "pick": 125,
    "position": "WR",
    "name": "Skyler Bell"
  },
  "HIB564972": {
    "round": 4,
    "pick": 133,
    "position": "TE",
    "name": "Matthew Hibner"
  },
  "LAN016345": {
    "round": 4,
    "pick": 136,
    "position": "WR",
    "name": "Bryce Lance"
  },
  "VIR271235": {
    "round": 5,
    "pick": 143,
    "position": "WR",
    "name": "Reggie Virgil"
  },
  "JOL735174": {
    "round": 5,
    "pick": 152,
    "position": "TE",
    "name": "Justin Joly"
  },
  "BRE060106": {
    "round": 5,
    "pick": 159,
    "position": "TE",
    "name": "Max Bredeson"
  },
  "JOH224817": {
    "round": 5,
    "pick": 161,
    "position": "RB",
    "name": "Emmett Johnson"
  },
  "KOZ404039": {
    "round": 5,
    "pick": 164,
    "position": "TE",
    "name": "Tanner Koziol"
  },
  "LAW090280": {
    "round": 5,
    "pick": 168,
    "position": "WR",
    "name": "Kendrick Law"
  },
  "NOW373761": {
    "round": 5,
    "pick": 169,
    "position": "TE",
    "name": "Riley Nowakowski"
  },
  "CUE040912": {
    "round": 5,
    "pick": 173,
    "position": "TE",
    "name": "Josh Cuevas"
  },
  "RAN022436": {
    "round": 5,
    "pick": 174,
    "position": "RB",
    "name": "Adam Randall"
  },
  "ALL092954": {
    "round": 5,
    "pick": 176,
    "position": "WR",
    "name": "Cyrus Allen"
  },
  "COL362413": {
    "round": 5,
    "pick": 177,
    "position": "WR",
    "name": "Kevin Coleman Jr."
  },
  "PAY546690": {
    "round": 5,
    "pick": 178,
    "position": "QB",
    "name": "Cole Payton"
  },
  "TRA291459": {
    "round": 5,
    "pick": 180,
    "position": "TE",
    "name": "Seydou Traore"
  },
  "GRE361852": {
    "round": 6,
    "pick": 182,
    "position": "QB",
    "name": "Taylen Green"
  },
  "SHA375359": {
    "round": 6,
    "pick": 185,
    "position": "TE",
    "name": "Bauer Sharp"
  },
  "ALL532376": {
    "round": 6,
    "pick": 187,
    "position": "RB",
    "name": "Kaytron Allen"
  },
  "BRO268113": {
    "round": 6,
    "pick": 190,
    "position": "WR",
    "name": "Barion Brown"
  },
  "CAM108646": {
    "round": 6,
    "pick": 191,
    "position": "WR",
    "name": "Josh Cameron"
  },
  "BEN601117": {
    "round": 6,
    "pick": 195,
    "position": "WR",
    "name": "Malik Benson"
  },
  "DAN490797": {
    "round": 6,
    "pick": 197,
    "position": "WR",
    "name": "CJ Daniels"
  },
  "CLA041524": {
    "round": 6,
    "pick": 198,
    "position": "RB",
    "name": "Demond Claiborne"
  },
  "HEN199637": {
    "round": 6,
    "pick": 199,
    "position": "WR",
    "name": "Emmanuel Henderson Jr."
  },
  "WIL189259": {
    "round": 6,
    "pick": 203,
    "position": "WR",
    "name": "CJ Williams"
  },
  "BON235618": {
    "round": 6,
    "pick": 204,
    "position": "WR",
    "name": "Lewis Bond"
  },
  "SMI038569": {
    "round": 7,
    "pick": 218,
    "position": "WR",
    "name": "Anthony Smith"
  },
  "END438361": {
    "round": 7,
    "pick": 221,
    "position": "TE",
    "name": "Jack Endries"
  },
  "KAL252591": {
    "round": 7,
    "pick": 223,
    "position": "QB",
    "name": "Athan Kaliakmanis"
  },
  "KAN023071": {
    "round": 7,
    "pick": 225,
    "position": "TE",
    "name": "Jaren Kanak"
  },
  "MOR767384": {
    "round": 7,
    "pick": 234,
    "position": "QB",
    "name": "Behren Morton"
  },
  "MCG547540": {
    "round": 7,
    "pick": 237,
    "position": "RB",
    "name": "Seth McGowan"
  },
  "MIL303300": {
    "round": 7,
    "pick": 245,
    "position": "RB",
    "name": "Jam Miller"
  },
  "RYA022232": {
    "round": 7,
    "pick": 248,
    "position": "TE",
    "name": "Carsen Ryan"
  },
  "NUS440041": {
    "round": 7,
    "pick": 249,
    "position": "QB",
    "name": "Garrett Nussmeier"
  },
  "BEN687044": {
    "round": 7,
    "pick": 256,
    "position": "TE",
    "name": "Dallen Bentley"
  }
};

export const DRAFT_PICKS_META = {
  baseline_start: 2015,
  baseline_end: 2025,
  current_class_season: 2026,
  generated_at: "2026-08-25T02:25:27.203232+00:00",
};
