// draft_picks.js — Gridiron Oracle rookie baseline data
// AUTO-GENERATED by scripts/fetch_draft_picks.py — DO NOT EDIT MANUALLY
// Baseline seasons: 2015-2025
// Current draft class: 2026
// Generated: 2026-09-06T03:54:26.907280+00:00
//
// ROUND_BASELINES: historical average rookie-season PPR points by
// position and round, used to project rookies with no nfl_data.js
// history. Built from real outcomes, not assumptions — but note this
// is a rough baseline, not a player-specific projection. A "good"
// or "bad" rookie within the same draft slot will vary widely; this
// gives a reasonable starting point rather than pretending precision.

export const ROUND_BASELINES = {
  "QB": {
    "1": {
      "mean": 13.3,
      "median": 13.3,
      "count": 37
    },
    "2": {
      "mean": 8.4,
      "median": 11.3,
      "count": 7
    },
    "3": {
      "mean": 4.1,
      "median": 1.0,
      "count": 16
    },
    "4": {
      "mean": 3.6,
      "median": 0.0,
      "count": 15
    },
    "5": {
      "mean": 3.4,
      "median": 0.7,
      "count": 15
    },
    "6": {
      "mean": 2.6,
      "median": 0.0,
      "count": 20
    },
    "7": {
      "mean": 1.8,
      "median": 0.0,
      "count": 17
    }
  },
  "RB": {
    "1": {
      "mean": 14.0,
      "median": 14.6,
      "count": 16
    },
    "2": {
      "mean": 10.3,
      "median": 11.6,
      "count": 24
    },
    "3": {
      "mean": 7.2,
      "median": 6.3,
      "count": 32
    },
    "4": {
      "mean": 5.7,
      "median": 5.9,
      "count": 48
    },
    "5": {
      "mean": 4.1,
      "median": 3.7,
      "count": 37
    },
    "6": {
      "mean": 2.5,
      "median": 2.2,
      "count": 37
    },
    "7": {
      "mean": 2.2,
      "median": 0.5,
      "count": 39
    }
  },
  "WR": {
    "1": {
      "mean": 9.4,
      "median": 9.3,
      "count": 49
    },
    "2": {
      "mean": 7.6,
      "median": 7.5,
      "count": 53
    },
    "3": {
      "mean": 4.8,
      "median": 4.0,
      "count": 50
    },
    "4": {
      "mean": 3.3,
      "median": 2.3,
      "count": 48
    },
    "5": {
      "mean": 3.9,
      "median": 1.8,
      "count": 45
    },
    "6": {
      "mean": 2.0,
      "median": 1.1,
      "count": 59
    },
    "7": {
      "mean": 1.5,
      "median": 0.0,
      "count": 53
    }
  },
  "TE": {
    "1": {
      "mean": 9.1,
      "median": 9.7,
      "count": 11
    },
    "2": {
      "mean": 5.3,
      "median": 4.9,
      "count": 20
    },
    "3": {
      "mean": 3.3,
      "median": 2.3,
      "count": 27
    },
    "4": {
      "mean": 4.7,
      "median": 4.6,
      "count": 30
    },
    "5": {
      "mean": 2.9,
      "median": 2.7,
      "count": 29
    },
    "6": {
      "mean": 1.4,
      "median": 0.0,
      "count": 21
    },
    "7": {
      "mean": 0.8,
      "median": 0.0,
      "count": 22
    }
  }
};

// CURRENT_DRAFT_CLASS: gsis_id -> round, pick, position, name
export const CURRENT_DRAFT_CLASS = {
  "00-0041562": {
    "round": 1,
    "pick": 1,
    "position": "QB",
    "name": "Fernando Mendoza"
  },
  "00-0041027": {
    "round": 1,
    "pick": 3,
    "position": "RB",
    "name": "Jeremiyah Love"
  },
  "00-0041438": {
    "round": 1,
    "pick": 4,
    "position": "WR",
    "name": "Carnell Tate"
  },
  "00-0041029": {
    "round": 1,
    "pick": 8,
    "position": "WR",
    "name": "Jordyn Tyson"
  },
  "00-0041568": {
    "round": 1,
    "pick": 13,
    "position": "QB",
    "name": "Ty Simpson"
  },
  "00-0041032": {
    "round": 1,
    "pick": 16,
    "position": "TE",
    "name": "Kenyon Sadiq"
  },
  "00-0040867": {
    "round": 1,
    "pick": 20,
    "position": "WR",
    "name": "Makai Lemon"
  },
  "00-0041547": {
    "round": 1,
    "pick": 24,
    "position": "WR",
    "name": "KC Concepcion"
  },
  "00-0041511": {
    "round": 1,
    "pick": 30,
    "position": "WR",
    "name": "Omar Cooper Jr."
  },
  "00-0041512": {
    "round": 1,
    "pick": 32,
    "position": "RB",
    "name": "Jadarian Price"
  },
  "00-0041035": {
    "round": 2,
    "pick": 33,
    "position": "WR",
    "name": "De'Zhaun Stribling"
  },
  "00-0041037": {
    "round": 2,
    "pick": 39,
    "position": "WR",
    "name": "Denzel Boston"
  },
  "00-0041489": {
    "round": 2,
    "pick": 47,
    "position": "WR",
    "name": "Germie Bernard"
  },
  "00-0041483": {
    "round": 2,
    "pick": 54,
    "position": "TE",
    "name": "Eli Stowers"
  },
  "00-0041503": {
    "round": 2,
    "pick": 56,
    "position": "TE",
    "name": "Nate Boerkircher"
  },
  "00-0041472": {
    "round": 2,
    "pick": 59,
    "position": "TE",
    "name": "Marlin Klein"
  },
  "00-0041510": {
    "round": 2,
    "pick": 61,
    "position": "TE",
    "name": "Max Klare"
  },
  "00-0041561": {
    "round": 3,
    "pick": 65,
    "position": "QB",
    "name": "Carson Beck"
  },
  "00-0041558": {
    "round": 3,
    "pick": 69,
    "position": "TE",
    "name": "Sam Roush"
  },
  "00-0041040": {
    "round": 3,
    "pick": 71,
    "position": "WR",
    "name": "Antonio Williams"
  },
  "00-0041041": {
    "round": 3,
    "pick": 73,
    "position": "TE",
    "name": "Oscar Delp"
  },
  "00-0041042": {
    "round": 3,
    "pick": 74,
    "position": "WR",
    "name": "Malachi Fields"
  },
  "00-0041523": {
    "round": 3,
    "pick": 75,
    "position": "WR",
    "name": "Caleb Douglas"
  },
  "00-0041565": {
    "round": 3,
    "pick": 76,
    "position": "QB",
    "name": "Drew Allar"
  },
  "00-0041044": {
    "round": 3,
    "pick": 79,
    "position": "WR",
    "name": "Zachariah Branch"
  },
  "00-0040870": {
    "round": 3,
    "pick": 80,
    "position": "WR",
    "name": "Ja'Kobi Lane"
  },
  "00-0041047": {
    "round": 3,
    "pick": 83,
    "position": "WR",
    "name": "Chris Brazzell II"
  },
  "00-0041048": {
    "round": 3,
    "pick": 84,
    "position": "WR",
    "name": "Ted Hurst"
  },
  "00-0041524": {
    "round": 3,
    "pick": 87,
    "position": "TE",
    "name": "Will Kacmarek"
  },
  "00-0041051": {
    "round": 3,
    "pick": 89,
    "position": "WR",
    "name": "Zavion Thomas"
  },
  "00-0041052": {
    "round": 3,
    "pick": 90,
    "position": "RB",
    "name": "Kaelon Black"
  },
  "00-0041525": {
    "round": 3,
    "pick": 94,
    "position": "WR",
    "name": "Chris Bell"
  },
  "00-0041395": {
    "round": 3,
    "pick": 95,
    "position": "TE",
    "name": "Eli Raridon"
  },
  "00-0041550": {
    "round": 4,
    "pick": 105,
    "position": "WR",
    "name": "Brenen Thompson"
  },
  "00-0041496": {
    "round": 4,
    "pick": 108,
    "position": "RB",
    "name": "Jonah Coleman"
  },
  "00-0041056": {
    "round": 4,
    "pick": 110,
    "position": "QB",
    "name": "Cade Klubnik"
  },
  "00-0040876": {
    "round": 4,
    "pick": 115,
    "position": "WR",
    "name": "Elijah Sarratt"
  },
  "00-0041397": {
    "round": 4,
    "pick": 121,
    "position": "WR",
    "name": "Kaden Wetjen"
  },
  "00-0040878": {
    "round": 4,
    "pick": 122,
    "position": "RB",
    "name": "Mike Washington Jr."
  },
  "00-0041443": {
    "round": 4,
    "pick": 125,
    "position": "WR",
    "name": "Skyler Bell"
  },
  "00-0040879": {
    "round": 4,
    "pick": 133,
    "position": "TE",
    "name": "Matthew Hibner"
  },
  "00-0041067": {
    "round": 4,
    "pick": 136,
    "position": "WR",
    "name": "Bryce Lance"
  },
  "00-0041069": {
    "round": 4,
    "pick": 140,
    "position": "WR",
    "name": "Colbie Young"
  },
  "00-0041070": {
    "round": 5,
    "pick": 143,
    "position": "WR",
    "name": "Reggie Virgil"
  },
  "00-0041077": {
    "round": 5,
    "pick": 152,
    "position": "TE",
    "name": "Justin Joly"
  },
  "00-0041081": {
    "round": 5,
    "pick": 159,
    "position": "TE",
    "name": "Max Bredeson"
  },
  "00-0041013": {
    "round": 5,
    "pick": 161,
    "position": "RB",
    "name": "Emmett Johnson"
  },
  "00-0041084": {
    "round": 5,
    "pick": 164,
    "position": "TE",
    "name": "Tanner Koziol"
  },
  "00-0040886": {
    "round": 5,
    "pick": 165,
    "position": "RB",
    "name": "Nicholas Singleton"
  },
  "00-0041446": {
    "round": 5,
    "pick": 168,
    "position": "WR",
    "name": "Kendrick Law"
  },
  "00-0041398": {
    "round": 5,
    "pick": 169,
    "position": "TE",
    "name": "Riley Nowakowski"
  },
  "00-0041087": {
    "round": 5,
    "pick": 170,
    "position": "TE",
    "name": "Joe Royer"
  },
  "00-0040887": {
    "round": 5,
    "pick": 173,
    "position": "TE",
    "name": "Josh Cuevas"
  },
  "00-0040888": {
    "round": 5,
    "pick": 174,
    "position": "RB",
    "name": "Adam Randall"
  },
  "00-0040890": {
    "round": 5,
    "pick": 176,
    "position": "WR",
    "name": "Cyrus Allen"
  },
  "00-0041529": {
    "round": 5,
    "pick": 177,
    "position": "WR",
    "name": "Kevin Coleman Jr."
  },
  "00-0040891": {
    "round": 5,
    "pick": 178,
    "position": "QB",
    "name": "Cole Payton"
  },
  "00-0041579": {
    "round": 5,
    "pick": 180,
    "position": "TE",
    "name": "Seydou Traore"
  },
  "00-0041092": {
    "round": 6,
    "pick": 182,
    "position": "QB",
    "name": "Taylen Green"
  },
  "00-0041094": {
    "round": 6,
    "pick": 185,
    "position": "TE",
    "name": "Bauer Sharp"
  },
  "00-0041096": {
    "round": 6,
    "pick": 187,
    "position": "RB",
    "name": "Kaytron Allen"
  },
  "00-0041099": {
    "round": 6,
    "pick": 190,
    "position": "WR",
    "name": "Barion Brown"
  },
  "00-0041100": {
    "round": 6,
    "pick": 191,
    "position": "WR",
    "name": "Josh Cameron"
  },
  "00-0040894": {
    "round": 6,
    "pick": 195,
    "position": "WR",
    "name": "Malik Benson"
  },
  "00-0041399": {
    "round": 6,
    "pick": 197,
    "position": "WR",
    "name": "CJ Daniels"
  },
  "00-0041104": {
    "round": 6,
    "pick": 198,
    "position": "RB",
    "name": "Demond Claiborne"
  },
  "00-0040895": {
    "round": 6,
    "pick": 199,
    "position": "WR",
    "name": "Emmanuel Henderson Jr."
  },
  "00-0041106": {
    "round": 6,
    "pick": 203,
    "position": "WR",
    "name": "CJ Williams"
  },
  "00-0041467": {
    "round": 6,
    "pick": 204,
    "position": "WR",
    "name": "Lewis Bond"
  },
  "00-0040900": {
    "round": 7,
    "pick": 218,
    "position": "WR",
    "name": "Anthony Smith"
  },
  "00-0041116": {
    "round": 7,
    "pick": 221,
    "position": "TE",
    "name": "Jack Endries"
  },
  "00-0041117": {
    "round": 7,
    "pick": 223,
    "position": "QB",
    "name": "Athan Kaliakmanis"
  },
  "00-0040901": {
    "round": 7,
    "pick": 225,
    "position": "TE",
    "name": "Jaren Kanak"
  },
  "00-0041123": {
    "round": 7,
    "pick": 234,
    "position": "QB",
    "name": "Behren Morton"
  },
  "00-0041125": {
    "round": 7,
    "pick": 237,
    "position": "RB",
    "name": "Seth McGowan"
  },
  "00-0041129": {
    "round": 7,
    "pick": 245,
    "position": "RB",
    "name": "Jam Miller"
  },
  "00-0041131": {
    "round": 7,
    "pick": 248,
    "position": "TE",
    "name": "Carsen Ryan"
  },
  "00-0040906": {
    "round": 7,
    "pick": 249,
    "position": "QB",
    "name": "Garrett Nussmeier"
  },
  "00-0041132": {
    "round": 7,
    "pick": 254,
    "position": "WR",
    "name": "Deion Burks"
  },
  "00-0041133": {
    "round": 7,
    "pick": 256,
    "position": "TE",
    "name": "Dallen Bentley"
  }
};

export const DRAFT_PICKS_META = {
  baseline_start: 2015,
  baseline_end: 2025,
  current_class_season: 2026,
  generated_at: "2026-09-06T03:54:26.907280+00:00",
};
