// espn_data.js — Gridiron Oracle ESPN roster data
// AUTO-GENERATED by scripts/fetch_espn_roster.py — DO NOT EDIT MANUALLY
// League: 839979 | Season: 2026 | Fetched: 2026-09-09T10:14:18.461099+00:00
// Team: Tennessee Standby4Recknng | Starters: 8 | Total: 13

export const ESPN_DATA = {
  "league": {
    "league_id": 839979,
    "season": 2026,
    "league_name": "#siscocks",
    "team_count": 12,
    "current_week": 1,
    "scoring_format": [
      {
        "abbr": "PA0",
        "label": "0 points allowed",
        "id": 89,
        "points": 5.0
      },
      {
        "abbr": "BLKKRTD",
        "label": "Blocked Punt or FG return for TD",
        "id": 93,
        "points": 6.0
      },
      {
        "abbr": "PY25",
        "label": "Every 25 passing yards",
        "id": 8,
        "points": 1.0
      },
      {
        "abbr": "PA1",
        "label": "1-6 points allowed",
        "id": 90,
        "points": 4.0
      },
      {
        "abbr": "PA28",
        "label": "28-34 points allowed",
        "id": 123,
        "points": -1.0
      },
      {
        "abbr": "YA449",
        "label": "400-449 total yards allowed",
        "id": 133,
        "points": -3.0
      },
      {
        "abbr": "RTD",
        "label": "TD Rush",
        "id": 25,
        "points": 6.0
      },
      {
        "abbr": "REC",
        "label": "Each reception",
        "id": 53,
        "points": 1.0
      },
      {
        "abbr": "YA499",
        "label": "450-499 total yards allowed",
        "id": 134,
        "points": -5.0
      },
      {
        "abbr": "FUML",
        "label": "Total Fumbles Lost",
        "id": 72,
        "points": -2.0
      },
      {
        "abbr": "YA549",
        "label": "500-549 total yards allowed",
        "id": 135,
        "points": -6.0
      },
      {
        "abbr": "INT",
        "label": "Each Interception",
        "id": 95,
        "points": 2.0
      },
      {
        "abbr": "YA550",
        "label": "550+ total yards allowed",
        "id": 136,
        "points": -7.0
      },
      {
        "abbr": "SF",
        "label": "Each Safety",
        "id": 98,
        "points": 2.0
      },
      {
        "abbr": "PA7",
        "label": "7-13 points allowed",
        "id": 91,
        "points": 3.0
      },
      {
        "abbr": "SK",
        "label": "Each Sack",
        "id": 99,
        "points": 1.0
      },
      {
        "abbr": "FR",
        "label": "Each Fumble Recovered",
        "id": 96,
        "points": 2.0
      },
      {
        "abbr": "2PC",
        "label": "2pt Passing Conversion",
        "id": 19,
        "points": 2.0
      },
      {
        "abbr": "RETD",
        "label": "TD Reception",
        "id": 43,
        "points": 6.0
      },
      {
        "abbr": "BLKK",
        "label": "Blocked Punt, PAT or FG",
        "id": 97,
        "points": 2.0
      },
      {
        "abbr": "PRTD",
        "label": "Punt Return TD",
        "id": 102,
        "points": 6.0
      },
      {
        "abbr": "PTD",
        "label": "TD Pass",
        "id": 4,
        "points": 4.0
      },
      {
        "abbr": "INTT",
        "label": "Interceptions Thrown",
        "id": 20,
        "points": -2.0
      },
      {
        "abbr": "KRTD",
        "label": "Kickoff Return TD",
        "id": 101,
        "points": 6.0
      },
      {
        "abbr": "FTD",
        "label": "Fumble Recovered for TD",
        "id": 63,
        "points": 6.0
      },
      {
        "abbr": "FG0",
        "label": "FG Made (0-39 yards)",
        "id": 80,
        "points": 3.0
      },
      {
        "abbr": "2PR",
        "label": "2pt Rushing Conversion",
        "id": 26,
        "points": 2.0
      },
      {
        "abbr": "FG40",
        "label": "FG Made (40-49 yards)",
        "id": 77,
        "points": 4.0
      },
      {
        "abbr": "YA100",
        "label": "Less than 100 total yards allowed",
        "id": 128,
        "points": 5.0
      },
      {
        "abbr": "PA14",
        "label": "14-17 points allowed",
        "id": 92,
        "points": 1.0
      },
      {
        "abbr": "PA46",
        "label": "46+ points allowed",
        "id": 125,
        "points": -5.0
      },
      {
        "abbr": "FGM",
        "label": "Total FG Missed",
        "id": 85,
        "points": -1.0
      },
      {
        "abbr": "PA35",
        "label": "35-45 points allowed",
        "id": 124,
        "points": -3.0
      },
      {
        "abbr": "YA399",
        "label": "350-399 total yards allowed",
        "id": 132,
        "points": -1.0
      },
      {
        "abbr": "PAT",
        "label": "Each PAT Made",
        "id": 86,
        "points": 1.0
      },
      {
        "abbr": "REY",
        "label": "Receiving Yards",
        "id": 42,
        "points": 0.1
      },
      {
        "abbr": "YA199",
        "label": "100-199 total yards allowed",
        "id": 129,
        "points": 3.0
      },
      {
        "abbr": "RY10",
        "label": "Every 10 rushing yards",
        "id": 28,
        "points": 1.0
      },
      {
        "abbr": "2PRE",
        "label": "2pt Receiving Conversion",
        "id": 44,
        "points": 2.0
      },
      {
        "abbr": "INTTD",
        "label": "Interception Return TD",
        "id": 103,
        "points": 6.0
      },
      {
        "abbr": "FG60",
        "label": "FG Made (60+ yards)",
        "id": 201,
        "points": 5.0
      },
      {
        "abbr": "YA299",
        "label": "200-299 total yards allowed",
        "id": 130,
        "points": 2.0
      },
      {
        "abbr": "FRTD",
        "label": "Fumble Return TD",
        "id": 104,
        "points": 6.0
      },
      {
        "abbr": "FG50",
        "label": "FG Made (50-59 yards)",
        "id": 198,
        "points": 5.0
      }
    ],
    "teams": [
      {
        "team_id": 7,
        "team_name": "Tennessee Standby4Recknng",
        "wins": 0,
        "losses": 0
      },
      {
        "team_id": 8,
        "team_name": "Super e-Bowl-a",
        "wins": 0,
        "losses": 0
      },
      {
        "team_id": 14,
        "team_name": "Kicked in the Nooksack!",
        "wins": 0,
        "losses": 0
      },
      {
        "team_id": 15,
        "team_name": "Hurts Me to Hurts You",
        "wins": 0,
        "losses": 0
      },
      {
        "team_id": 18,
        "team_name": "Blue Steel",
        "wins": 0,
        "losses": 0
      },
      {
        "team_id": 21,
        "team_name": "Local Sports Team",
        "wins": 0,
        "losses": 0
      },
      {
        "team_id": 23,
        "team_name": "Los Pollos Hermanos",
        "wins": 0,
        "losses": 0
      },
      {
        "team_id": 24,
        "team_name": "Jackie Moon",
        "wins": 0,
        "losses": 0
      },
      {
        "team_id": 25,
        "team_name": "spokane  sanders",
        "wins": 0,
        "losses": 0
      },
      {
        "team_id": 27,
        "team_name": "Kettle King",
        "wins": 0,
        "losses": 0
      },
      {
        "team_id": 28,
        "team_name": "Wild Thornberries",
        "wins": 0,
        "losses": 0
      },
      {
        "team_id": 29,
        "team_name": "Luck of the Irish",
        "wins": 0,
        "losses": 0
      }
    ]
  },
  "my_team": {
    "team_id": 7,
    "team_name": "Tennessee Standby4Recknng",
    "wins": 0,
    "losses": 0
  },
  "roster": [
    {
      "espn_id": "4362238",
      "name": "Chase Brown",
      "position": "RB",
      "team": "CIN",
      "lineup_slot": "RB",
      "on_bench": false,
      "on_ir": false,
      "injury_status": "ACTIVE",
      "play_probability": 1.0,
      "injury_detail": "",
      "avg_points": 0.0,
      "total_points": 0.0,
      "projected_points": 15.94
    },
    {
      "espn_id": "4047646",
      "name": "A.J. Brown",
      "position": "WR",
      "team": "NE",
      "lineup_slot": "WR",
      "on_bench": false,
      "on_ir": false,
      "injury_status": "ACTIVE",
      "play_probability": 1.0,
      "injury_detail": "",
      "avg_points": 0.0,
      "total_points": 0.0,
      "projected_points": 14.67
    },
    {
      "espn_id": "4426354",
      "name": "George Pickens",
      "position": "WR",
      "team": "DAL",
      "lineup_slot": "WR",
      "on_bench": false,
      "on_ir": false,
      "injury_status": "ACTIVE",
      "play_probability": 1.0,
      "injury_detail": "",
      "avg_points": 0.0,
      "total_points": 0.0,
      "projected_points": 14.07
    },
    {
      "espn_id": "4569618",
      "name": "Garrett Wilson",
      "position": "WR",
      "team": "NYJ",
      "lineup_slot": "BENCH",
      "on_bench": true,
      "on_ir": false,
      "injury_status": "ACTIVE",
      "play_probability": 1.0,
      "injury_detail": "",
      "avg_points": 0.0,
      "total_points": 0.0,
      "projected_points": 14.71
    },
    {
      "espn_id": "4882093",
      "name": "Bhayshul Tuten",
      "position": "RB",
      "team": "JAX",
      "lineup_slot": "RB",
      "on_bench": false,
      "on_ir": false,
      "injury_status": "QUESTIONABLE",
      "play_probability": 0.55,
      "injury_detail": "QUESTIONABLE",
      "avg_points": 0.0,
      "total_points": 0.0,
      "projected_points": 12.09
    },
    {
      "espn_id": "4426338",
      "name": "Bo Nix",
      "position": "QB",
      "team": "DEN",
      "lineup_slot": "QB",
      "on_bench": false,
      "on_ir": false,
      "injury_status": "ACTIVE",
      "play_probability": 1.0,
      "injury_detail": "",
      "avg_points": 0.0,
      "total_points": 0.0,
      "projected_points": 17.3
    },
    {
      "espn_id": "4361050",
      "name": "Isaiah Likely",
      "position": "TE",
      "team": "NYG",
      "lineup_slot": "TE",
      "on_bench": false,
      "on_ir": false,
      "injury_status": "ACTIVE",
      "play_probability": 1.0,
      "injury_detail": "",
      "avg_points": 0.0,
      "total_points": 0.0,
      "projected_points": 9.12
    },
    {
      "espn_id": "4429096",
      "name": "Blake Corum",
      "position": "RB",
      "team": "LAR",
      "lineup_slot": "BENCH",
      "on_bench": true,
      "on_ir": false,
      "injury_status": "ACTIVE",
      "play_probability": 1.0,
      "injury_detail": "",
      "avg_points": 0.0,
      "total_points": 0.0,
      "projected_points": 9.33
    },
    {
      "espn_id": "4429025",
      "name": "Quentin Johnston",
      "position": "WR",
      "team": "LAC",
      "lineup_slot": "BENCH",
      "on_bench": true,
      "on_ir": false,
      "injury_status": "ACTIVE",
      "play_probability": 1.0,
      "injury_detail": "",
      "avg_points": 0.0,
      "total_points": 0.0,
      "projected_points": 9.72
    },
    {
      "espn_id": "4362249",
      "name": "Jayden Reed",
      "position": "WR",
      "team": "GB",
      "lineup_slot": "BENCH",
      "on_bench": true,
      "on_ir": false,
      "injury_status": "ACTIVE",
      "play_probability": 1.0,
      "injury_detail": "",
      "avg_points": 0.0,
      "total_points": 0.0,
      "projected_points": 10.18
    },
    {
      "espn_id": "3054850",
      "name": "Alvin Kamara",
      "position": "RB",
      "team": "NO",
      "lineup_slot": "BENCH",
      "on_bench": true,
      "on_ir": false,
      "injury_status": "QUESTIONABLE",
      "play_probability": 0.55,
      "injury_detail": "QUESTIONABLE",
      "avg_points": 0.0,
      "total_points": 0.0,
      "projected_points": 7.55
    },
    {
      "espn_id": "17427",
      "name": "Cairo Santos",
      "position": "K",
      "team": "CHI",
      "lineup_slot": "K",
      "on_bench": false,
      "on_ir": false,
      "injury_status": "ACTIVE",
      "play_probability": 1.0,
      "injury_detail": "",
      "avg_points": 0.0,
      "total_points": 0.0,
      "projected_points": 8.48
    },
    {
      "espn_id": "-16024",
      "name": "Chargers D/ST",
      "position": "DST",
      "team": "LAC",
      "lineup_slot": "DST",
      "on_bench": false,
      "on_ir": false,
      "injury_status": "NORMAL",
      "play_probability": 1.0,
      "injury_detail": "NORMAL",
      "avg_points": 0.0,
      "total_points": 0.0,
      "projected_points": 5.56
    }
  ],
  "matchup": {
    "week": 1,
    "my_team_id": 7,
    "opp_team_id": 8,
    "opp_team_name": "Super e-Bowl-a",
    "my_projected": 113.62,
    "opp_projected": 116.94,
    "my_actual": 0.0,
    "opp_actual": 0.0
  },
  "fetched_at": "2026-09-09T10:14:18.461099+00:00",
  "offseason": false
};

export const MY_ROSTER  = ESPN_DATA.roster;
export const MY_TEAM    = ESPN_DATA.my_team;
export const MATCHUP    = ESPN_DATA.matchup;
export const LEAGUE     = ESPN_DATA.league;
export const FETCHED_AT = ESPN_DATA.fetched_at;
export const OFFSEASON  = ESPN_DATA.offseason;
