// espn_data.js — Gridiron Oracle ESPN roster data
// AUTO-GENERATED by scripts/fetch_espn_roster.py — DO NOT EDIT MANUALLY
// League: 839979 | Season: 2025 | Fetched: 2026-03-21T09:44:49.302593+00:00
// Team: Tennessee Standby4Recknng | Starters: 8 | Total: 14

export const ESPN_DATA = {
  "league": {
    "league_id": 839979,
    "season": 2025,
    "league_name": "#siscocks",
    "team_count": 12,
    "current_week": 17,
    "scoring_format": [
      {
        "abbr": "PA0",
        "label": "0 points allowed",
        "id": 89,
        "points": 5.0
      },
      {
        "abbr": "BLKKRTD",
        "label": "Blocked Punt or FG return for TD",
        "id": 93,
        "points": 6.0
      },
      {
        "abbr": "PY25",
        "label": "Every 25 passing yards",
        "id": 8,
        "points": 1.0
      },
      {
        "abbr": "PA1",
        "label": "1-6 points allowed",
        "id": 90,
        "points": 4.0
      },
      {
        "abbr": "PA28",
        "label": "28-34 points allowed",
        "id": 123,
        "points": -1.0
      },
      {
        "abbr": "YA449",
        "label": "400-449 total yards allowed",
        "id": 133,
        "points": -3.0
      },
      {
        "abbr": "RTD",
        "label": "TD Rush",
        "id": 25,
        "points": 6.0
      },
      {
        "abbr": "REC",
        "label": "Each reception",
        "id": 53,
        "points": 1.0
      },
      {
        "abbr": "YA499",
        "label": "450-499 total yards allowed",
        "id": 134,
        "points": -5.0
      },
      {
        "abbr": "FUML",
        "label": "Total Fumbles Lost",
        "id": 72,
        "points": -2.0
      },
      {
        "abbr": "YA549",
        "label": "500-549 total yards allowed",
        "id": 135,
        "points": -6.0
      },
      {
        "abbr": "INT",
        "label": "Each Interception",
        "id": 95,
        "points": 2.0
      },
      {
        "abbr": "YA550",
        "label": "550+ total yards allowed",
        "id": 136,
        "points": -7.0
      },
      {
        "abbr": "SF",
        "label": "Each Safety",
        "id": 98,
        "points": 2.0
      },
      {
        "abbr": "PA7",
        "label": "7-13 points allowed",
        "id": 91,
        "points": 3.0
      },
      {
        "abbr": "SK",
        "label": "Each Sack",
        "id": 99,
        "points": 1.0
      },
      {
        "abbr": "FR",
        "label": "Each Fumble Recovered",
        "id": 96,
        "points": 2.0
      },
      {
        "abbr": "2PC",
        "label": "2pt Passing Conversion",
        "id": 19,
        "points": 2.0
      },
      {
        "abbr": "RETD",
        "label": "TD Reception",
        "id": 43,
        "points": 6.0
      },
      {
        "abbr": "BLKK",
        "label": "Blocked Punt, PAT or FG",
        "id": 97,
        "points": 2.0
      },
      {
        "abbr": "PRTD",
        "label": "Punt Return TD",
        "id": 102,
        "points": 6.0
      },
      {
        "abbr": "PTD",
        "label": "TD Pass",
        "id": 4,
        "points": 4.0
      },
      {
        "abbr": "INTT",
        "label": "Interceptions Thrown",
        "id": 20,
        "points": -2.0
      },
      {
        "abbr": "KRTD",
        "label": "Kickoff Return TD",
        "id": 101,
        "points": 6.0
      },
      {
        "abbr": "FTD",
        "label": "Fumble Recovered for TD",
        "id": 63,
        "points": 6.0
      },
      {
        "abbr": "FG0",
        "label": "FG Made (0-39 yards)",
        "id": 80,
        "points": 3.0
      },
      {
        "abbr": "2PR",
        "label": "2pt Rushing Conversion",
        "id": 26,
        "points": 2.0
      },
      {
        "abbr": "FG40",
        "label": "FG Made (40-49 yards)",
        "id": 77,
        "points": 4.0
      },
      {
        "abbr": "YA100",
        "label": "Less than 100 total yards allowed",
        "id": 128,
        "points": 5.0
      },
      {
        "abbr": "PA14",
        "label": "14-17 points allowed",
        "id": 92,
        "points": 1.0
      },
      {
        "abbr": "PA46",
        "label": "46+ points allowed",
        "id": 125,
        "points": -5.0
      },
      {
        "abbr": "FGM",
        "label": "Total FG Missed",
        "id": 85,
        "points": -1.0
      },
      {
        "abbr": "PA35",
        "label": "35-45 points allowed",
        "id": 124,
        "points": -3.0
      },
      {
        "abbr": "YA399",
        "label": "350-399 total yards allowed",
        "id": 132,
        "points": -1.0
      },
      {
        "abbr": "PAT",
        "label": "Each PAT Made",
        "id": 86,
        "points": 1.0
      },
      {
        "abbr": "REY",
        "label": "Receiving Yards",
        "id": 42,
        "points": 0.1
      },
      {
        "abbr": "YA199",
        "label": "100-199 total yards allowed",
        "id": 129,
        "points": 3.0
      },
      {
        "abbr": "RY10",
        "label": "Every 10 rushing yards",
        "id": 28,
        "points": 1.0
      },
      {
        "abbr": "2PRE",
        "label": "2pt Receiving Conversion",
        "id": 44,
        "points": 2.0
      },
      {
        "abbr": "INTTD",
        "label": "Interception Return TD",
        "id": 103,
        "points": 6.0
      },
      {
        "abbr": "FG60",
        "label": "FG Made (60+ yards)",
        "id": 201,
        "points": 5.0
      },
      {
        "abbr": "YA299",
        "label": "200-299 total yards allowed",
        "id": 130,
        "points": 2.0
      },
      {
        "abbr": "FRTD",
        "label": "Fumble Return TD",
        "id": 104,
        "points": 6.0
      },
      {
        "abbr": "FG50",
        "label": "FG Made (50-59 yards)",
        "id": 198,
        "points": 5.0
      }
    ],
    "teams": [
      {
        "team_id": 7,
        "team_name": "Tennessee Standby4Recknng",
        "wins": 17,
        "losses": 11
      },
      {
        "team_id": 8,
        "team_name": "Super e-Bowl-a",
        "wins": 7,
        "losses": 21
      },
      {
        "team_id": 14,
        "team_name": "Kicked in the Nooksack!",
        "wins": 18,
        "losses": 10
      },
      {
        "team_id": 15,
        "team_name": "Hurts Me to Hurts You",
        "wins": 15,
        "losses": 13
      },
      {
        "team_id": 18,
        "team_name": "Blue Steel",
        "wins": 11,
        "losses": 17
      },
      {
        "team_id": 21,
        "team_name": "Local Sports Team",
        "wins": 8,
        "losses": 20
      },
      {
        "team_id": 23,
        "team_name": "Los Pollos Hermanos",
        "wins": 9,
        "losses": 19
      },
      {
        "team_id": 24,
        "team_name": "Jackie Moon",
        "wins": 16,
        "losses": 12
      },
      {
        "team_id": 25,
        "team_name": "spokane  sanders",
        "wins": 16,
        "losses": 12
      },
      {
        "team_id": 27,
        "team_name": "Kettle King",
        "wins": 13,
        "losses": 15
      },
      {
        "team_id": 28,
        "team_name": "Wild Thornberries",
        "wins": 20,
        "losses": 8
      },
      {
        "team_id": 29,
        "team_name": "Luck of the Irish",
        "wins": 18,
        "losses": 10
      }
    ]
  },
  "my_team": {
    "team_id": 7,
    "team_name": "Tennessee Standby4Recknng",
    "wins": 17,
    "losses": 11
  },
  "roster": [
    {
      "espn_id": "4426502",
      "name": "Drake London",
      "position": "WR",
      "team": "ATL",
      "lineup_slot": "BENCH",
      "on_bench": true,
      "on_ir": false,
      "injury_status": "ACTIVE",
      "play_probability": 1.0,
      "injury_detail": "",
      "avg_points": 16.82,
      "total_points": 201.9,
      "projected_points": 15.73
    },
    {
      "espn_id": "4596448",
      "name": "Bucky Irving",
      "position": "RB",
      "team": "TB",
      "lineup_slot": "RB",
      "on_bench": false,
      "on_ir": false,
      "injury_status": "ACTIVE",
      "play_probability": 1.0,
      "injury_detail": "",
      "avg_points": 13.47,
      "total_points": 134.7,
      "projected_points": 16.62
    },
    {
      "espn_id": "3128429",
      "name": "Courtland Sutton",
      "position": "WR",
      "team": "DEN",
      "lineup_slot": "WR",
      "on_bench": false,
      "on_ir": false,
      "injury_status": "ACTIVE",
      "play_probability": 1.0,
      "injury_detail": "",
      "avg_points": 12.92,
      "total_points": 219.7,
      "projected_points": 13.39
    },
    {
      "espn_id": "2577417",
      "name": "Dak Prescott",
      "position": "QB",
      "team": "DAL",
      "lineup_slot": "QB",
      "on_bench": false,
      "on_ir": false,
      "injury_status": "ACTIVE",
      "play_probability": 1.0,
      "injury_detail": "",
      "avg_points": 17.71,
      "total_points": 301.0,
      "projected_points": 16.73
    },
    {
      "espn_id": "4608686",
      "name": "Kyle Monangai",
      "position": "RB",
      "team": "CHI",
      "lineup_slot": "BENCH",
      "on_bench": true,
      "on_ir": false,
      "injury_status": "ACTIVE",
      "play_probability": 1.0,
      "injury_detail": "",
      "avg_points": 8.14,
      "total_points": 138.4,
      "projected_points": 3.02
    },
    {
      "espn_id": "4362249",
      "name": "Jayden Reed",
      "position": "WR",
      "team": "GB",
      "lineup_slot": "BENCH",
      "on_bench": true,
      "on_ir": false,
      "injury_status": "ACTIVE",
      "play_probability": 1.0,
      "injury_detail": "",
      "avg_points": 6.81,
      "total_points": 47.7,
      "projected_points": 10.4
    },
    {
      "espn_id": "4241474",
      "name": "Brian Robinson Jr.",
      "position": "RB",
      "team": "SF",
      "lineup_slot": "BENCH",
      "on_bench": true,
      "on_ir": false,
      "injury_status": "ACTIVE",
      "play_probability": 1.0,
      "injury_detail": "",
      "avg_points": 3.44,
      "total_points": 58.5,
      "projected_points": 4.45
    },
    {
      "espn_id": "4430539",
      "name": "Brenton Strange",
      "position": "TE",
      "team": "JAX",
      "lineup_slot": "BENCH",
      "on_bench": true,
      "on_ir": false,
      "injury_status": "ACTIVE",
      "play_probability": 1.0,
      "injury_detail": "",
      "avg_points": 9.83,
      "total_points": 118.0,
      "projected_points": 8.2
    },
    {
      "espn_id": "3116165",
      "name": "Chris Godwin Jr.",
      "position": "WR",
      "team": "TB",
      "lineup_slot": "WR",
      "on_bench": false,
      "on_ir": false,
      "injury_status": "ACTIVE",
      "play_probability": 1.0,
      "injury_detail": "",
      "avg_points": 9.22,
      "total_points": 83.0,
      "projected_points": 14.42
    },
    {
      "espn_id": "5083076",
      "name": "Harold Fannin Jr.",
      "position": "TE",
      "team": "CLE",
      "lineup_slot": "TE",
      "on_bench": false,
      "on_ir": false,
      "injury_status": "QUESTIONABLE",
      "play_probability": 0.55,
      "injury_detail": "QUESTIONABLE",
      "avg_points": 11.57,
      "total_points": 185.1,
      "projected_points": 3.15
    },
    {
      "espn_id": "4685278",
      "name": "Luther Burden III",
      "position": "WR",
      "team": "CHI",
      "lineup_slot": "IR",
      "on_bench": true,
      "on_ir": true,
      "injury_status": "ACTIVE",
      "play_probability": 1.0,
      "injury_detail": "",
      "avg_points": 8.41,
      "total_points": 126.2,
      "projected_points": 5.34
    },
    {
      "espn_id": "4240657",
      "name": "Michael Carter",
      "position": "RB",
      "team": "ARI",
      "lineup_slot": "RB",
      "on_bench": false,
      "on_ir": false,
      "injury_status": "ACTIVE",
      "play_probability": 1.0,
      "injury_detail": "",
      "avg_points": 7.13,
      "total_points": 92.7,
      "projected_points": 0.0
    },
    {
      "espn_id": "-16008",
      "name": "Lions D/ST",
      "position": "DST",
      "team": "DET",
      "lineup_slot": "DST",
      "on_bench": false,
      "on_ir": false,
      "injury_status": "NORMAL",
      "play_probability": 1.0,
      "injury_detail": "NORMAL",
      "avg_points": 5.35,
      "total_points": 91.0,
      "projected_points": 7.21
    },
    {
      "espn_id": "2971573",
      "name": "Ka'imi Fairbairn",
      "position": "K",
      "team": "HOU",
      "lineup_slot": "K",
      "on_bench": false,
      "on_ir": false,
      "injury_status": "ACTIVE",
      "play_probability": 1.0,
      "injury_detail": "",
      "avg_points": 12.67,
      "total_points": 190.0,
      "projected_points": 7.99
    }
  ],
  "matchup": {
    "week": 17,
    "my_team_id": 7,
    "opp_team_id": 29,
    "opp_team_name": "Luck of the Irish",
    "my_projected": 99.0,
    "opp_projected": 135.8,
    "my_actual": 99.0,
    "opp_actual": 135.8
  },
  "fetched_at": "2026-03-21T09:44:49.302593+00:00",
  "offseason": false
};

export const MY_ROSTER  = ESPN_DATA.roster;
export const MY_TEAM    = ESPN_DATA.my_team;
export const MATCHUP    = ESPN_DATA.matchup;
export const LEAGUE     = ESPN_DATA.league;
export const FETCHED_AT = ESPN_DATA.fetched_at;
export const OFFSEASON  = ESPN_DATA.offseason;
