// espn_aav.js — AUTO-GENERATED by scripts/fetch_espn_aav.py
// Source: ESPN Fantasy Football API (kona_player_info)
// Real platform-wide Average Auction Value — not a calculation.
// Fetched: 2026-09-04T11:35:45.591356+00:00
// DO NOT EDIT BY HAND

// Keyed by GSIS ID for direct use in DraftBoard.jsx
export const ESPN_AAV_BY_GSIS = {
  "00-0039139": {
    "name": "Jahmyr Gibbs",
    "position": "RB",
    "aav": 70.69,
    "aav_change": 0.01
  },
  "00-0038542": {
    "name": "Bijan Robinson",
    "position": "RB",
    "aav": 68.26,
    "aav_change": 0.0
  },
  "00-0036900": {
    "name": "Ja'Marr Chase",
    "position": "WR",
    "aav": 62.94,
    "aav_change": 0.14
  },
  "00-0039075": {
    "name": "Puka Nacua",
    "position": "WR",
    "aav": 60.04,
    "aav_change": -0.01
  },
  "00-0038543": {
    "name": "Jaxon Smith-Njigba",
    "position": "WR",
    "aav": 59.96,
    "aav_change": -0.03
  },
  "00-0036223": {
    "name": "Jonathan Taylor",
    "position": "RB",
    "aav": 58.76,
    "aav_change": 0.08
  },
  "00-0036963": {
    "name": "Amon-Ra St. Brown",
    "position": "WR",
    "aav": 57.77,
    "aav_change": 0.01
  },
  "00-0033280": {
    "name": "Christian McCaffrey",
    "position": "RB",
    "aav": 56.44,
    "aav_change": 0.01
  },
  "00-0037248": {
    "name": "James Cook III",
    "position": "RB",
    "aav": 54.48,
    "aav_change": 0.24
  },
  "00-0036358": {
    "name": "CeeDee Lamb",
    "position": "WR",
    "aav": 51.18,
    "aav_change": 0.03
  },
  "00-0036322": {
    "name": "Justin Jefferson",
    "position": "WR",
    "aav": 50.84,
    "aav_change": 0.03
  },
  "00-0039040": {
    "name": "De'Von Achane",
    "position": "RB",
    "aav": 48.96,
    "aav_change": -0.25
  },
  "00-0034844": {
    "name": "Saquon Barkley",
    "position": "RB",
    "aav": 48.14,
    "aav_change": 0.19
  },
  "00-0038597": {
    "name": "Chase Brown",
    "position": "RB",
    "aav": 44.17,
    "aav_change": 0.33
  },
  "00-0040666": {
    "name": "Omarion Hampton",
    "position": "RB",
    "aav": 43.43,
    "aav_change": 0.45
  },
  "00-0032764": {
    "name": "Derrick Henry",
    "position": "RB",
    "aav": 43.41,
    "aav_change": 0.19
  },
  "00-0034857": {
    "name": "Josh Allen",
    "position": "QB",
    "aav": 39.41,
    "aav_change": 0.33
  },
  "00-0040122": {
    "name": "Ashton Jeanty",
    "position": "RB",
    "aav": 37.65,
    "aav_change": -0.17
  },
  "00-0035676": {
    "name": "A.J. Brown",
    "position": "WR",
    "aav": 37.42,
    "aav_change": 0.16
  },
  "00-0037238": {
    "name": "Drake London",
    "position": "WR",
    "aav": 37.03,
    "aav_change": -0.27
  },
  "00-0038134": {
    "name": "Kenneth Walker III",
    "position": "RB",
    "aav": 36.74,
    "aav_change": -0.03
  },
  "00-0037744": {
    "name": "Trey McBride",
    "position": "TE",
    "aav": 33.77,
    "aav_change": -0.25
  },
  "00-0039338": {
    "name": "Brock Bowers",
    "position": "TE",
    "aav": 33.66,
    "aav_change": 0.02
  },
  "00-0041027": {
    "name": "Jeremiyah Love",
    "position": "RB",
    "aav": 33.57,
    "aav_change": -0.11
  },
  "00-0036554": {
    "name": "Nico Collins",
    "position": "WR",
    "aav": 33.33,
    "aav_change": 0.14
  },
  "00-0037247": {
    "name": "George Pickens",
    "position": "WR",
    "aav": 30.16,
    "aav_change": 0.18
  },
  "00-0037239": {
    "name": "Chris Olave",
    "position": "WR",
    "aav": 29.76,
    "aav_change": 0.09
  },
  "00-0039067": {
    "name": "Rashee Rice",
    "position": "WR",
    "aav": 29.26,
    "aav_change": -0.31
  },
  "00-0036997": {
    "name": "Javonte Williams",
    "position": "RB",
    "aav": 27.74,
    "aav_change": 0.12
  },
  "00-0039337": {
    "name": "Malik Nabers",
    "position": "WR",
    "aav": 27.25,
    "aav_change": -0.15
  },
  "00-0037840": {
    "name": "Kyren Williams",
    "position": "RB",
    "aav": 26.62,
    "aav_change": 0.29
  },
  "00-0038120": {
    "name": "Breece Hall",
    "position": "RB",
    "aav": 25.59,
    "aav_change": -0.1
  },
  "00-0034796": {
    "name": "Lamar Jackson",
    "position": "QB",
    "aav": 24.31,
    "aav_change": 0.47
  },
  "00-0036912": {
    "name": "DeVonta Smith",
    "position": "WR",
    "aav": 23.7,
    "aav_change": 0.11
  },
  "00-0037740": {
    "name": "Garrett Wilson",
    "position": "WR",
    "aav": 23.1,
    "aav_change": -0.08
  },
  "00-0036973": {
    "name": "Travis Etienne Jr.",
    "position": "RB",
    "aav": 21.73,
    "aav_change": 0.14
  },
  "00-0040129": {
    "name": "Emeka Egbuka",
    "position": "WR",
    "aav": 20.6,
    "aav_change": 0.0
  },
  "00-0039915": {
    "name": "Ladd McConkey",
    "position": "WR",
    "aav": 20.56,
    "aav_change": 0.12
  },
  "00-0039064": {
    "name": "Zay Flowers",
    "position": "WR",
    "aav": 20.33,
    "aav_change": 0.01
  },
  "00-0040124": {
    "name": "Tetairoa McMillan",
    "position": "WR",
    "aav": 19.88,
    "aav_change": -0.1
  },
  "00-0040126": {
    "name": "Colston Loveland",
    "position": "TE",
    "aav": 18.53,
    "aav_change": 0.18
  },
  "00-0040715": {
    "name": "Cam Skattebo",
    "position": "RB",
    "aav": 18.28,
    "aav_change": -0.12
  },
  "00-0040784": {
    "name": "Quinshon Judkins",
    "position": "RB",
    "aav": 18.09,
    "aav_change": 0.06
  },
  "00-0031381": {
    "name": "Davante Adams",
    "position": "WR",
    "aav": 17.5,
    "aav_change": -0.02
  },
  "00-0036410": {
    "name": "Tee Higgins",
    "position": "WR",
    "aav": 16.65,
    "aav_change": 0.13
  },
  "00-0036275": {
    "name": "D'Andre Swift",
    "position": "RB",
    "aav": 16.61,
    "aav_change": 0.25
  },
  "00-0036613": {
    "name": "Jaylen Waddle",
    "position": "WR",
    "aav": 16.45,
    "aav_change": -0.06
  },
  "00-0039851": {
    "name": "Drake Maye",
    "position": "QB",
    "aav": 16.38,
    "aav_change": 0.07
  },
  "00-0039910": {
    "name": "Jayden Daniels",
    "position": "QB",
    "aav": 15.0,
    "aav_change": 0.06
  },
  "00-0036442": {
    "name": "Joe Burrow",
    "position": "QB",
    "aav": 14.55,
    "aav_change": 0.21
  },
  "00-0039361": {
    "name": "Bucky Irving",
    "position": "RB",
    "aav": 14.31,
    "aav_change": -0.14
  },
  "00-0036389": {
    "name": "Jalen Hurts",
    "position": "QB",
    "aav": 13.54,
    "aav_change": 0.02
  },
  "00-0040719": {
    "name": "Bhayshul Tuten",
    "position": "RB",
    "aav": 13.53,
    "aav_change": 0.19
  },
  "00-0041512": {
    "name": "Jadarian Price",
    "position": "RB",
    "aav": 13.33,
    "aav_change": 0.18
  },
  "00-0034827": {
    "name": "DJ Moore",
    "position": "WR",
    "aav": 13.09,
    "aav_change": 0.16
  },
  "00-0035685": {
    "name": "David Montgomery",
    "position": "RB",
    "aav": 12.38,
    "aav_change": 0.05
  },
  "00-0040128": {
    "name": "Tyler Warren",
    "position": "TE",
    "aav": 12.33,
    "aav_change": -0.04
  },
  "00-0035700": {
    "name": "Josh Jacobs",
    "position": "RB",
    "aav": 12.31,
    "aav_change": -1.99
  },
  "00-0035659": {
    "name": "Terry McLaurin",
    "position": "WR",
    "aav": 11.39,
    "aav_change": -0.1
  },
  "00-0037240": {
    "name": "Jameson Williams",
    "position": "WR",
    "aav": 10.67,
    "aav_change": 0.06
  },
  "00-0039919": {
    "name": "Rome Odunze",
    "position": "WR",
    "aav": 10.56,
    "aav_change": -0.13
  },
  "00-0033077": {
    "name": "Dak Prescott",
    "position": "QB",
    "aav": 9.08,
    "aav_change": 0.09
  },
  "00-0040735": {
    "name": "Luther Burden III",
    "position": "WR",
    "aav": 8.94,
    "aav_change": 0.02
  },
  "00-0039918": {
    "name": "Caleb Williams",
    "position": "QB",
    "aav": 7.68,
    "aav_change": 0.11
  },
  "00-0040734": {
    "name": "TreVeyon Henderson",
    "position": "RB",
    "aav": 7.51,
    "aav_change": 0.03
  },
  "00-0040691": {
    "name": "Jaxson Dart",
    "position": "QB",
    "aav": 7.49,
    "aav_change": 0.03
  },
  "00-0036355": {
    "name": "Justin Herbert",
    "position": "QB",
    "aav": 7.42,
    "aav_change": 0.08
  },
  "00-0039849": {
    "name": "Marvin Harrison Jr.",
    "position": "WR",
    "aav": 7.02,
    "aav_change": 0.06
  },
  "00-0036875": {
    "name": "Rhamondre Stevenson",
    "position": "RB",
    "aav": 6.82,
    "aav_change": 0.06
  },
  "00-0041438": {
    "name": "Carnell Tate",
    "position": "WR",
    "aav": 6.65,
    "aav_change": -0.12
  },
  "00-0026498": {
    "name": "Matthew Stafford",
    "position": "QB",
    "aav": 6.45,
    "aav_change": 0.05
  },
  "00-0036970": {
    "name": "Kyle Pitts Sr.",
    "position": "TE",
    "aav": 6.37,
    "aav_change": -0.05
  },
  "00-0031408": {
    "name": "Mike Evans",
    "position": "WR",
    "aav": 6.3,
    "aav_change": 0.08
  },
  "00-0039732": {
    "name": "Bo Nix",
    "position": "QB",
    "aav": 6.29,
    "aav_change": 0.01
  },
  "00-0036971": {
    "name": "Trevor Lawrence",
    "position": "QB",
    "aav": 6.23,
    "aav_change": -0.01
  },
  "00-0038606": {
    "name": "Parker Washington",
    "position": "WR",
    "aav": 6.09,
    "aav_change": 0.03
  },
  "00-0038124": {
    "name": "Christian Watson",
    "position": "WR",
    "aav": 5.92,
    "aav_change": 0.1
  },
  "00-0039065": {
    "name": "Sam LaPorta",
    "position": "TE",
    "aav": 5.82,
    "aav_change": -0.04
  },
  "00-0033873": {
    "name": "Patrick Mahomes",
    "position": "QB",
    "aav": 5.77,
    "aav_change": 0.0
  },
  "00-0040663": {
    "name": "Harold Fannin Jr.",
    "position": "TE",
    "aav": 5.53,
    "aav_change": 0.0
  },
  "00-0033288": {
    "name": "George Kittle",
    "position": "TE",
    "aav": 5.5,
    "aav_change": 0.17
  },
  "00-0034348": {
    "name": "Courtland Sutton",
    "position": "WR",
    "aav": 5.5,
    "aav_change": -0.05
  },
  "00-0035640": {
    "name": "DK Metcalf",
    "position": "WR",
    "aav": 5.39,
    "aav_change": -0.01
  },
  "00-0035261": {
    "name": "Tony Pollard",
    "position": "RB",
    "aav": 5.38,
    "aav_change": 0.12
  },
  "00-0037228": {
    "name": "Jaylen Warren",
    "position": "RB",
    "aav": 5.0,
    "aav_change": 0.16
  },
  "00-0037834": {
    "name": "Brock Purdy",
    "position": "QB",
    "aav": 4.76,
    "aav_change": 0.02
  },
  "00-0038996": {
    "name": "Tucker Kraft",
    "position": "TE",
    "aav": 4.52,
    "aav_change": 0.02
  },
  "00-0036252": {
    "name": "Michael Pittman Jr.",
    "position": "WR",
    "aav": 4.3,
    "aav_change": 0.0
  },
  "00-0039811": {
    "name": "MarShawn Lloyd",
    "position": "RB",
    "aav": 4.25,
    "aav_change": 0.42
  },
  "00-0036139": {
    "name": "Rico Dowdle",
    "position": "RB",
    "aav": 4.18,
    "aav_change": 0.02
  },
  "00-0039344": {
    "name": "Jonathon Brooks",
    "position": "RB",
    "aav": 4.11,
    "aav_change": 0.02
  },
  "00-0036158": {
    "name": "J.K. Dobbins",
    "position": "RB",
    "aav": 3.25,
    "aav_change": 0.04
  },
  "00-0037664": {
    "name": "Alec Pierce",
    "position": "WR",
    "aav": 3.17,
    "aav_change": 0.02
  },
  "00-0035228": {
    "name": "Kyler Murray",
    "position": "QB",
    "aav": 3.11,
    "aav_change": 0.01
  },
  "00-0030506": {
    "name": "Travis Kelce",
    "position": "TE",
    "aav": 3.07,
    "aav_change": -0.01
  },
  "00-0033106": {
    "name": "Jared Goff",
    "position": "QB",
    "aav": 3.01,
    "aav_change": 0.0
  },
  "00-0036919": {
    "name": "Kenny Gainwell",
    "position": "RB",
    "aav": 2.97,
    "aav_change": 0.06
  },
  "00-0038559": {
    "name": "Michael Wilson",
    "position": "WR",
    "aav": 2.96,
    "aav_change": 0.01
  },
  "00-0031588": {
    "name": "Stefon Diggs",
    "position": "WR",
    "aav": 2.96,
    "aav_change": 0.04
  },
  "00-0039893": {
    "name": "Brian Thomas Jr.",
    "position": "WR",
    "aav": 2.83,
    "aav_change": -0.01
  },
  "00-0039738": {
    "name": "Blake Corum",
    "position": "RB",
    "aav": 2.82,
    "aav_change": 0.05
  },
  "00-0036555": {
    "name": "Chuba Hubbard",
    "position": "RB",
    "aav": 2.65,
    "aav_change": 0.03
  },
  "00-0040667": {
    "name": "Matthew Golden",
    "position": "WR",
    "aav": 2.42,
    "aav_change": -0.06
  },
  "00-0034855": {
    "name": "Baker Mayfield",
    "position": "QB",
    "aav": 2.31,
    "aav_change": 0.01
  },
  "00-0041035": {
    "name": "De'Zhaun Stribling",
    "position": "WR",
    "aav": 2.29,
    "aav_change": 0.07
  },
  "00-0037525": {
    "name": "Jordan Mason",
    "position": "RB",
    "aav": 2.28,
    "aav_change": 0.03
  },
  "00-0034351": {
    "name": "Dallas Goedert",
    "position": "TE",
    "aav": 2.27,
    "aav_change": 0.01
  },
  "00-0033921": {
    "name": "Chris Godwin Jr.",
    "position": "WR",
    "aav": 2.26,
    "aav_change": 0.05
  },
  "00-0038117": {
    "name": "Wan'Dale Robinson",
    "position": "WR",
    "aav": 2.22,
    "aav_change": 0.0
  },
  "00-0038994": {
    "name": "Jordan Addison",
    "position": "WR",
    "aav": 2.16,
    "aav_change": -0.04
  },
  "00-0033293": {
    "name": "Aaron Jones Sr.",
    "position": "RB",
    "aav": 2.1,
    "aav_change": 0.0
  },
  "00-0040236": {
    "name": "Kyle Monangai",
    "position": "RB",
    "aav": 2.08,
    "aav_change": 0.02
  },
  "00-0037838": {
    "name": "Isaiah Likely",
    "position": "TE",
    "aav": 2.04,
    "aav_change": 0.03
  },
  "00-0038544": {
    "name": "Quentin Johnston",
    "position": "WR",
    "aav": 2.0,
    "aav_change": 0.02
  },
  "00-0040743": {
    "name": "Tyler Shough",
    "position": "QB",
    "aav": 1.97,
    "aav_change": 0.0
  },
  "00-0040242": {
    "name": "Jacory Croskey-Merritt",
    "position": "RB",
    "aav": 1.96,
    "aav_change": 0.01
  },
  "00-0038041": {
    "name": "Jake Ferguson",
    "position": "TE",
    "aav": 1.93,
    "aav_change": -0.03
  },
  "00-0040730": {
    "name": "RJ Harvey",
    "position": "RB",
    "aav": 1.93,
    "aav_change": 0.01
  },
  "00-0036264": {
    "name": "Jordan Love",
    "position": "QB",
    "aav": 1.93,
    "aav_change": 0.0
  },
  "00-0040718": {
    "name": "Travis Hunter",
    "position": "WR",
    "aav": 1.67,
    "aav_change": 0.01
  },
  "00-0040867": {
    "name": "Makai Lemon",
    "position": "WR",
    "aav": 1.61,
    "aav_change": -0.01
  },
  "00-0034960": {
    "name": "Jakobi Meyers",
    "position": "WR",
    "aav": 1.6,
    "aav_change": -0.02
  },
  "00-0037256": {
    "name": "Rachaad White",
    "position": "RB",
    "aav": 1.58,
    "aav_change": 0.02
  },
  "00-0039894": {
    "name": "Xavier Worthy",
    "position": "WR",
    "aav": 1.57,
    "aav_change": -0.02
  },
  "00-0038933": {
    "name": "Dalton Kincaid",
    "position": "TE",
    "aav": 1.53,
    "aav_change": -0.01
  },
  "00-0034753": {
    "name": "Mark Andrews",
    "position": "TE",
    "aav": 1.52,
    "aav_change": 0.0
  },
  "00-0038997": {
    "name": "Josh Downs",
    "position": "WR",
    "aav": 1.38,
    "aav_change": -0.01
  },
  "00-0041547": {
    "name": "KC Concepcion",
    "position": "WR",
    "aav": 1.35,
    "aav_change": -0.01
  },
  "00-0039146": {
    "name": "Jayden Reed",
    "position": "WR",
    "aav": 1.34,
    "aav_change": -0.01
  },
  "00-0035710": {
    "name": "Daniel Jones",
    "position": "QB",
    "aav": 1.33,
    "aav_change": -0.01
  },
  "00-0034869": {
    "name": "Sam Darnold",
    "position": "QB",
    "aav": 1.21,
    "aav_change": -0.01
  },
  "00-0037746": {
    "name": "Brian Robinson Jr.",
    "position": "RB",
    "aav": 1.18,
    "aav_change": 0.01
  },
  "00-0039165": {
    "name": "Zach Charbonnet",
    "position": "RB",
    "aav": 1.16,
    "aav_change": 0.01
  },
  "00-0035719": {
    "name": "Deebo Samuel Sr.",
    "position": "WR",
    "aav": 1.14,
    "aav_change": -0.04
  },
  "00-0037261": {
    "name": "Khalil Shakir",
    "position": "WR",
    "aav": 1.12,
    "aav_change": -0.02
  },
  "00-0037816": {
    "name": "Romeo Doubs",
    "position": "WR",
    "aav": 1.04,
    "aav_change": 0.01
  },
  "00-0040583": {
    "name": "Woody Marks",
    "position": "RB",
    "aav": 1.03,
    "aav_change": 0.0
  },
  "00-0038128": {
    "name": "Malik Willis",
    "position": "QB",
    "aav": 0.93,
    "aav_change": -0.03
  },
  "WAS569019": {
    "name": "Mike Washington Jr.",
    "position": "RB",
    "aav": 0.91,
    "aav_change": 0.0
  },
  "00-0039163": {
    "name": "C.J. Stroud",
    "position": "QB",
    "aav": 0.91,
    "aav_change": -0.02
  },
  "00-0039032": {
    "name": "Tyjae Spears",
    "position": "RB",
    "aav": 0.9,
    "aav_change": 0.02
  },
  "00-0039491": {
    "name": "Jalen Coker",
    "position": "WR",
    "aav": 0.84,
    "aav_change": 0.0
  },
  "00-0035229": {
    "name": "T.J. Hockenson",
    "position": "TE",
    "aav": 0.72,
    "aav_change": -0.04
  },
  "00-0033090": {
    "name": "Hunter Henry",
    "position": "TE",
    "aav": 0.67,
    "aav_change": -0.02
  },
  "00-0037545": {
    "name": "Rashid Shaheed",
    "position": "WR",
    "aav": 0.64,
    "aav_change": -0.01
  },
  "00-0037263": {
    "name": "Tyler Allgeier",
    "position": "RB",
    "aav": 0.64,
    "aav_change": 0.01
  },
  "00-0041496": {
    "name": "Jonah Coleman",
    "position": "RB",
    "aav": 0.6,
    "aav_change": 0.03
  },
  "00-0036040": {
    "name": "Juwan Johnson",
    "position": "TE",
    "aav": 0.59,
    "aav_change": 0.01
  },
  "00-0037197": {
    "name": "Isiah Pacheco",
    "position": "RB",
    "aav": 0.59,
    "aav_change": -0.02
  },
  "00-0038611": {
    "name": "Chris Rodriguez Jr.",
    "position": "RB",
    "aav": 0.57,
    "aav_change": 0.02
  },
  "00-0033906": {
    "name": "Alvin Kamara",
    "position": "RB",
    "aav": 0.56,
    "aav_change": -0.01
  },
  "00-0041029": {
    "name": "Jordyn Tyson",
    "position": "WR",
    "aav": 0.55,
    "aav_change": 0.01
  },
  "00-0039855": {
    "name": "Jalen McMillan",
    "position": "WR",
    "aav": 0.55,
    "aav_change": 0.02
  },
  "00-0039150": {
    "name": "Bryce Young",
    "position": "QB",
    "aav": 0.47,
    "aav_change": -0.02
  },
  "00-0038977": {
    "name": "Tank Dell",
    "position": "WR",
    "aav": 0.45,
    "aav_change": -0.02
  },
  "00-0040676": {
    "name": "Cam Ward",
    "position": "QB",
    "aav": 0.45,
    "aav_change": -0.02
  },
  "00-0041032": {
    "name": "Kenyon Sadiq",
    "position": "TE",
    "aav": 0.42,
    "aav_change": -0.04
  },
  "00-0038454": {
    "name": "Keaton Mitchell",
    "position": "RB",
    "aav": 0.41,
    "aav_change": 0.01
  },
  "00-0038563": {
    "name": "Tre Tucker",
    "position": "WR",
    "aav": 0.38,
    "aav_change": -0.01
  },
  "00-0030279": {
    "name": "Keenan Allen",
    "position": "WR",
    "aav": 0.37,
    "aav_change": 0.01
  },
  "00-0040737": {
    "name": "Terrance Ferguson",
    "position": "TE",
    "aav": 0.35,
    "aav_change": 0.0
  },
  "00-0038555": {
    "name": "Tank Bigsby",
    "position": "RB",
    "aav": 0.35,
    "aav_change": 0.01
  },
  "00-0041037": {
    "name": "Denzel Boston",
    "position": "WR",
    "aav": 0.33,
    "aav_change": 0.0
  },
  "00-0036407": {
    "name": "Jerry Jeudy",
    "position": "WR",
    "aav": 0.31,
    "aav_change": 0.0
  },
  "00-0034837": {
    "name": "Calvin Ridley",
    "position": "WR",
    "aav": 0.28,
    "aav_change": 0.0
  },
  "00-0039794": {
    "name": "Braelon Allen",
    "position": "RB",
    "aav": 0.28,
    "aav_change": 0.0
  },
  "00-0041562": {
    "name": "Fernando Mendoza",
    "position": "QB",
    "aav": 0.28,
    "aav_change": -0.01
  },
  "00-0023459": {
    "name": "Aaron Rodgers",
    "position": "QB",
    "aav": 0.28,
    "aav_change": -0.01
  },
  "00-0038935": {
    "name": "Brenton Strange",
    "position": "TE",
    "aav": 0.27,
    "aav_change": -0.01
  },
  "00-0033119": {
    "name": "Jacoby Brissett",
    "position": "QB",
    "aav": 0.27,
    "aav_change": -0.01
  },
  "00-0040870": {
    "name": "Ja'Kobi Lane",
    "position": "WR",
    "aav": 0.26,
    "aav_change": 0.0
  },
  "00-0040162": {
    "name": "Dylan Sampson",
    "position": "RB",
    "aav": 0.26,
    "aav_change": 0.01
  },
  "00-0037291": {
    "name": "Jalen Nailor",
    "position": "WR",
    "aav": 0.26,
    "aav_change": -0.01
  },
  "00-0034975": {
    "name": "Justice Hill",
    "position": "RB",
    "aav": 0.24,
    "aav_change": 0.0
  },
  "00-0041052": {
    "name": "Kaelon Black",
    "position": "RB",
    "aav": 0.23,
    "aav_change": 0.01
  },
  "00-0030565": {
    "name": "Geno Smith",
    "position": "QB",
    "aav": 0.21,
    "aav_change": 0.0
  },
  "00-0041523": {
    "name": "Caleb Douglas",
    "position": "WR",
    "aav": 0.2,
    "aav_change": 0.0
  },
  "00-0039890": {
    "name": "Adonai Mitchell",
    "position": "WR",
    "aav": 0.19,
    "aav_change": 0.01
  },
  "00-0038393": {
    "name": "Dontayvion Wicks",
    "position": "WR",
    "aav": 0.19,
    "aav_change": -0.01
  },
  "00-0033908": {
    "name": "Cooper Kupp",
    "position": "WR",
    "aav": 0.16,
    "aav_change": 0.0
  },
  "00-0039875": {
    "name": "Ray Davis",
    "position": "RB",
    "aav": 0.16,
    "aav_change": 0.0
  },
  "00-0036550": {
    "name": "Rashod Bateman",
    "position": "WR",
    "aav": 0.16,
    "aav_change": -0.01
  },
  "00-0034383": {
    "name": "Dalton Schultz",
    "position": "TE",
    "aav": 0.15,
    "aav_change": 0.0
  },
  "00-0036893": {
    "name": "Najee Harris",
    "position": "RB",
    "aav": 0.15,
    "aav_change": 0.01
  },
  "00-0041013": {
    "name": "Emmett Johnson",
    "position": "RB",
    "aav": 0.15,
    "aav_change": 0.02
  },
  "00-0038608": {
    "name": "Kayshon Boutte",
    "position": "WR",
    "aav": 0.14,
    "aav_change": 0.0
  },
  "00-0039424": {
    "name": "Devaughn Vele",
    "position": "WR",
    "aav": 0.13,
    "aav_change": 0.0
  },
  "00-0039880": {
    "name": "Malik Washington",
    "position": "WR",
    "aav": 0.13,
    "aav_change": 0.0
  },
  "00-0036894": {
    "name": "Pat Freiermuth",
    "position": "TE",
    "aav": 0.11,
    "aav_change": -0.01
  },
  "00-0033526": {
    "name": "Samaje Perine",
    "position": "RB",
    "aav": 0.11,
    "aav_change": 0.02
  },
  "00-0040890": {
    "name": "Cyrus Allen",
    "position": "WR",
    "aav": 0.11,
    "aav_change": 0.0
  },
  "00-0040138": {
    "name": "Jaylin Noel",
    "position": "WR",
    "aav": 0.1,
    "aav_change": 0.0
  },
  "00-0033537": {
    "name": "Deshaun Watson",
    "position": "QB",
    "aav": 0.1,
    "aav_change": -0.01
  },
  "00-0036259": {
    "name": "Jauan Jennings",
    "position": "WR",
    "aav": 0.09,
    "aav_change": 0.0
  },
  "00-0037809": {
    "name": "Chig Okonkwo",
    "position": "TE",
    "aav": 0.09,
    "aav_change": 0.0
  },
  "00-0039793": {
    "name": "AJ Barner",
    "position": "TE",
    "aav": 0.08,
    "aav_change": 0.0
  },
  "00-0033885": {
    "name": "David Njoku",
    "position": "TE",
    "aav": 0.08,
    "aav_change": 0.0
  },
  "00-0031235": {
    "name": "Odell Beckham Jr.",
    "position": "WR",
    "aav": 0.08,
    "aav_change": 0.01
  },
  "00-0029604": {
    "name": "Kirk Cousins",
    "position": "QB",
    "aav": 0.08,
    "aav_change": 0.0
  },
  "00-0040142": {
    "name": "Kaleb Johnson",
    "position": "RB",
    "aav": 0.07,
    "aav_change": 0.01
  },
  "00-0041042": {
    "name": "Malachi Fields",
    "position": "WR",
    "aav": 0.07,
    "aav_change": 0.0
  },
  "00-0040668": {
    "name": "Shedeur Sanders",
    "position": "QB",
    "aav": 0.07,
    "aav_change": 0.0
  },
  "00-0039384": {
    "name": "Tyrone Tracy Jr.",
    "position": "RB",
    "aav": 0.06,
    "aav_change": -0.01
  },
  "00-0040727": {
    "name": "Tre' Harris",
    "position": "WR",
    "aav": 0.06,
    "aav_change": 0.0
  },
  "00-0036212": {
    "name": "Tua Tagovailoa",
    "position": "QB",
    "aav": 0.06,
    "aav_change": 0.0
  },
  "00-0041489": {
    "name": "Germie Bernard",
    "position": "WR",
    "aav": 0.05,
    "aav_change": 0.0
  },
  "00-0041511": {
    "name": "Omar Cooper Jr.",
    "position": "WR",
    "aav": 0.05,
    "aav_change": 0.0
  },
  "00-0040584": {
    "name": "Gunnar Helm",
    "position": "TE",
    "aav": 0.05,
    "aav_change": 0.0
  },
  "00-0041044": {
    "name": "Zachariah Branch",
    "position": "WR",
    "aav": 0.05,
    "aav_change": 0.0
  },
  "00-0039410": {
    "name": "Ryan Flournoy",
    "position": "WR",
    "aav": 0.05,
    "aav_change": 0.0
  },
  "00-0039391": {
    "name": "Kimani Vidal",
    "position": "RB",
    "aav": 0.05,
    "aav_change": 0.0
  },
  "00-0040177": {
    "name": "Jordan James",
    "position": "RB",
    "aav": 0.05,
    "aav_change": 0.0
  },
  "00-0040705": {
    "name": "Chimere Dike",
    "position": "WR",
    "aav": 0.05,
    "aav_change": 0.0
  },
  "00-0039917": {
    "name": "Michael Penix Jr.",
    "position": "QB",
    "aav": 0.05,
    "aav_change": -0.01
  },
  "00-0037252": {
    "name": "Greg Dulcich",
    "position": "TE",
    "aav": 0.04,
    "aav_change": 0.0
  },
  "00-0040669": {
    "name": "Isaac TeSlaa",
    "position": "WR",
    "aav": 0.04,
    "aav_change": 0.0
  },
  "00-0033040": {
    "name": "Tyreek Hill",
    "position": "WR",
    "aav": 0.04,
    "aav_change": 0.0
  },
  "00-0041525": {
    "name": "Chris Bell",
    "position": "WR",
    "aav": 0.04,
    "aav_change": 0.0
  },
  "00-0037563": {
    "name": "Malik Davis",
    "position": "RB",
    "aav": 0.04,
    "aav_change": 0.0
  },
  "00-0039874": {
    "name": "Jaylen Wright",
    "position": "RB",
    "aav": 0.04,
    "aav_change": 0.0
  },
  "00-0040134": {
    "name": "Pat Bryant",
    "position": "WR",
    "aav": 0.04,
    "aav_change": 0.0
  },
  "00-0037801": {
    "name": "KaVontae Turpin",
    "position": "WR",
    "aav": 0.04,
    "aav_change": 0.0
  },
  "00-0040189": {
    "name": "Oronde Gadsden",
    "position": "TE",
    "aav": 0.03,
    "aav_change": 0.0
  },
  "00-0033881": {
    "name": "Evan Engram",
    "position": "TE",
    "aav": 0.03,
    "aav_change": -0.01
  },
  "00-0040586": {
    "name": "Jaydon Blue",
    "position": "RB",
    "aav": 0.03,
    "aav_change": -0.01
  },
  "00-0038685": {
    "name": "Chris Brooks",
    "position": "RB",
    "aav": 0.02,
    "aav_change": 0.0
  },
  "00-0039299": {
    "name": "George Holani",
    "position": "RB",
    "aav": 0.02,
    "aav_change": 0.0
  },
  "00-0031610": {
    "name": "Darren Waller",
    "position": "TE",
    "aav": 0.02,
    "aav_change": 0.0
  },
  "00-0038129": {
    "name": "Cade Otton",
    "position": "TE",
    "aav": 0.02,
    "aav_change": 0.0
  },
  "00-0041040": {
    "name": "Antonio Williams",
    "position": "WR",
    "aav": 0.02,
    "aav_change": 0.0
  },
  "00-0039901": {
    "name": "Keon Coleman",
    "position": "WR",
    "aav": 0.02,
    "aav_change": 0.0
  },
  "00-0036309": {
    "name": "Darnell Mooney",
    "position": "WR",
    "aav": 0.02,
    "aav_change": 0.0
  },
  "00-0039342": {
    "name": "Xavier Legette",
    "position": "WR",
    "aav": 0.02,
    "aav_change": 0.0
  },
  "00-0040886": {
    "name": "Nicholas Singleton",
    "position": "RB",
    "aav": 0.02,
    "aav_change": 0.0
  },
  "00-0035537": {
    "name": "Ty Johnson",
    "position": "RB",
    "aav": 0.02,
    "aav_change": 0.0
  },
  "00-0034829": {
    "name": "Mike Gesicki",
    "position": "TE",
    "aav": 0.02,
    "aav_change": 0.0
  },
  "00-0038558": {
    "name": "Darnell Washington",
    "position": "TE",
    "aav": 0.02,
    "aav_change": 0.0
  },
  "00-0040198": {
    "name": "Ollie Gordon II",
    "position": "RB",
    "aav": 0.02,
    "aav_change": 0.0
  },
  "00-0041051": {
    "name": "Zavion Thomas",
    "position": "WR",
    "aav": 0.02,
    "aav_change": 0.0
  },
  "00-0041096": {
    "name": "Kaytron Allen",
    "position": "RB",
    "aav": 0.02,
    "aav_change": 0.0
  },
  "00-0039066": {
    "name": "Michael Mayer",
    "position": "TE",
    "aav": 0.02,
    "aav_change": 0.0
  },
  "00-0041561": {
    "name": "Carson Beck",
    "position": "QB",
    "aav": 0.02,
    "aav_change": 0.0
  },
  "00-0036290": {
    "name": "Cole Kmet",
    "position": "TE",
    "aav": 0.02,
    "aav_change": -0.01
  },
  "00-0039923": {
    "name": "J.J. McCarthy",
    "position": "QB",
    "aav": 0.02,
    "aav_change": 0.0
  },
  "00-0041125": {
    "name": "Seth McGowan",
    "position": "RB",
    "aav": 0.02,
    "aav_change": 0.0
  },
  "00-0022942": {
    "name": "Philip Rivers",
    "position": "QB",
    "aav": 0.02,
    "aav_change": -0.02
  },
  "00-0039471": {
    "name": "Frank Gore Jr.",
    "position": "RB",
    "aav": 0.02,
    "aav_change": 0.0
  },
  "00-0041467": {
    "name": "Lewis Bond",
    "position": "WR",
    "aav": 0.02,
    "aav_change": 0.0
  },
  "00-0032156": {
    "name": "Trevor Siemian",
    "position": "QB",
    "aav": 0.02,
    "aav_change": 0.0
  },
  "00-0036534": {
    "name": "Shane Zylstra",
    "position": "TE",
    "aav": 0.02,
    "aav_change": 0.0
  },
  "00-0033553": {
    "name": "James Conner",
    "position": "RB",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0037112": {
    "name": "Jake Tonges",
    "position": "TE",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0038896": {
    "name": "Jacob Saylors",
    "position": "RB",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0039868": {
    "name": "Troy Franklin",
    "position": "WR",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0035535": {
    "name": "Darius Slayton",
    "position": "WR",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0036244": {
    "name": "Colby Parkinson",
    "position": "TE",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0037741": {
    "name": "Jahan Dotson",
    "position": "WR",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0040729": {
    "name": "Jack Bech",
    "position": "WR",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0037666": {
    "name": "Jalen Tolbert",
    "position": "WR",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0038621": {
    "name": "DeMario Douglas",
    "position": "WR",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0041048": {
    "name": "Ted Hurst III",
    "position": "WR",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0038104": {
    "name": "Tyquan Thornton",
    "position": "WR",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0038951": {
    "name": "Sean Tucker",
    "position": "RB",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0035689": {
    "name": "Dawson Knox",
    "position": "TE",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0038976": {
    "name": "Marvin Mims Jr.",
    "position": "WR",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0041104": {
    "name": "Demond Claiborne",
    "position": "RB",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0040648": {
    "name": "Tory Horton",
    "position": "WR",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0039798": {
    "name": "Isaiah Davis",
    "position": "RB",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0041443": {
    "name": "Skyler Bell",
    "position": "WR",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0038705": {
    "name": "Emari Demercado",
    "position": "RB",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0034775": {
    "name": "Christian Kirk",
    "position": "WR",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0038551": {
    "name": "Kendre Miller",
    "position": "RB",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0040888": {
    "name": "Adam Randall",
    "position": "RB",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0038618": {
    "name": "Xavier Hutchinson",
    "position": "WR",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0040078": {
    "name": "Brashard Smith",
    "position": "RB",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0040238": {
    "name": "LeQuint Allen Jr.",
    "position": "RB",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0041483": {
    "name": "Eli Stowers",
    "position": "TE",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0039746": {
    "name": "Will Shipley",
    "position": "RB",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0035662": {
    "name": "Hollywood Brown",
    "position": "WR",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0039847": {
    "name": "Theo Johnson",
    "position": "TE",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0040644": {
    "name": "Trevor Etienne",
    "position": "RB",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0040179": {
    "name": "DJ Giddens",
    "position": "RB",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0040736": {
    "name": "Mason Taylor",
    "position": "TE",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0040739": {
    "name": "Elijah Arroyo",
    "position": "TE",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0036945": {
    "name": "Justin Fields",
    "position": "QB",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0041568": {
    "name": "Ty Simpson",
    "position": "QB",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0033110": {
    "name": "Tyler Higbee",
    "position": "TE",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0039355": {
    "name": "Luke McCaffrey",
    "position": "WR",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0026158": {
    "name": "Joe Flacco",
    "position": "QB",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0031503": {
    "name": "Jameis Winston",
    "position": "QB",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0036637": {
    "name": "Noah Gray",
    "position": "TE",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0034791": {
    "name": "Nick Chubb",
    "position": "RB",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0038476": {
    "name": "Tommy DeVito",
    "position": "QB",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0040785": {
    "name": "Dohnte Meyers",
    "position": "WR",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0040930": {
    "name": "Camden Brown",
    "position": "WR",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0033045": {
    "name": "Ezekiel Elliott",
    "position": "RB",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0041251": {
    "name": "Jalon Daniels",
    "position": "QB",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0040315": {
    "name": "Ja'Corey Brooks",
    "position": "WR",
    "aav": 0.01,
    "aav_change": 0.0
  },
  "00-0040900": {
    "name": "Anthony Smith",
    "position": "WR",
    "aav": 0.01,
    "aav_change": 0.0
  }
};

export const ESPN_AAV_META = {
  source: "ESPN Fantasy Football API",
  season: 2026,
  fetched_at: "2026-09-04T11:35:45.591356+00:00",
  player_count: 299,
};
