// weather_data.js — Gridiron Oracle game-day weather
// AUTO-GENERATED by scripts/fetch_weather.py — DO NOT EDIT MANUALLY
// Fetched: 2026-09-09T10:11:37.450204+00:00
// Flagged games: BUF, CAR, CHI, CIN, CLE, DEN, GB, JAX, KC, MIA, NE, NYG, NYJ, PHI, PIT, TB, TEN, WSH, BAL

export const WEATHER_DATA = {
  "ARI": {
    "team": "ARI",
    "stadium": "State Farm Stadium",
    "dome": true,
    "flags": [
      "DOME"
    ],
    "wind_mph": 0,
    "temp_f": 72,
    "precip_code": 0,
    "description": "Dome \u2014 no weather impact",
    "advisory": [
      "Dome \u2014 positive passing environment"
    ]
  },
  "ATL": {
    "team": "ATL",
    "stadium": "Mercedes-Benz Stadium",
    "dome": true,
    "flags": [
      "DOME"
    ],
    "wind_mph": 0,
    "temp_f": 72,
    "precip_code": 0,
    "description": "Dome \u2014 no weather impact",
    "advisory": [
      "Dome \u2014 positive passing environment"
    ]
  },
  "BUF": {
    "team": "BUF",
    "stadium": "Highmark Stadium",
    "dome": false,
    "flags": [
      "PRECIP"
    ],
    "wind_mph": 18.8,
    "temp_f": 57.8,
    "precip_code": 51,
    "description": "rain/snow expected",
    "advisory": [
      "Rain/snow \u2014 upgrade RB, downgrade WR ceiling"
    ]
  },
  "CAR": {
    "team": "CAR",
    "stadium": "Bank of America Stadium",
    "dome": false,
    "flags": [
      "PRECIP"
    ],
    "wind_mph": 10.3,
    "temp_f": 74.5,
    "precip_code": 51,
    "description": "rain/snow expected",
    "advisory": [
      "Rain/snow \u2014 upgrade RB, downgrade WR ceiling"
    ]
  },
  "CHI": {
    "team": "CHI",
    "stadium": "Soldier Field",
    "dome": false,
    "flags": [
      "PRECIP"
    ],
    "wind_mph": 10.1,
    "temp_f": 66.8,
    "precip_code": 51,
    "description": "rain/snow expected",
    "advisory": [
      "Rain/snow \u2014 upgrade RB, downgrade WR ceiling"
    ]
  },
  "CIN": {
    "team": "CIN",
    "stadium": "Paycor Stadium",
    "dome": false,
    "flags": [
      "PRECIP"
    ],
    "wind_mph": 12.9,
    "temp_f": 72.4,
    "precip_code": 95,
    "description": "rain/snow expected",
    "advisory": [
      "Rain/snow \u2014 upgrade RB, downgrade WR ceiling"
    ]
  },
  "CLE": {
    "team": "CLE",
    "stadium": "Huntington Bank Field",
    "dome": false,
    "flags": [
      "PRECIP"
    ],
    "wind_mph": 18.9,
    "temp_f": 68.1,
    "precip_code": 80,
    "description": "rain/snow expected",
    "advisory": [
      "Rain/snow \u2014 upgrade RB, downgrade WR ceiling"
    ]
  },
  "DAL": {
    "team": "DAL",
    "stadium": "AT&T Stadium",
    "dome": true,
    "flags": [
      "DOME"
    ],
    "wind_mph": 0,
    "temp_f": 72,
    "precip_code": 0,
    "description": "Dome \u2014 no weather impact",
    "advisory": [
      "Dome \u2014 positive passing environment"
    ]
  },
  "DEN": {
    "team": "DEN",
    "stadium": "Empower Field",
    "dome": false,
    "flags": [
      "PRECIP"
    ],
    "wind_mph": 14.5,
    "temp_f": 67.5,
    "precip_code": 53,
    "description": "rain/snow expected",
    "advisory": [
      "Rain/snow \u2014 upgrade RB, downgrade WR ceiling"
    ]
  },
  "DET": {
    "team": "DET",
    "stadium": "Ford Field",
    "dome": true,
    "flags": [
      "DOME"
    ],
    "wind_mph": 0,
    "temp_f": 72,
    "precip_code": 0,
    "description": "Dome \u2014 no weather impact",
    "advisory": [
      "Dome \u2014 positive passing environment"
    ]
  },
  "GB": {
    "team": "GB",
    "stadium": "Lambeau Field",
    "dome": false,
    "flags": [
      "PRECIP"
    ],
    "wind_mph": 16.9,
    "temp_f": 61.1,
    "precip_code": 80,
    "description": "rain/snow expected",
    "advisory": [
      "Rain/snow \u2014 upgrade RB, downgrade WR ceiling"
    ]
  },
  "HOU": {
    "team": "HOU",
    "stadium": "NRG Stadium",
    "dome": true,
    "flags": [
      "DOME"
    ],
    "wind_mph": 0,
    "temp_f": 72,
    "precip_code": 0,
    "description": "Dome \u2014 no weather impact",
    "advisory": [
      "Dome \u2014 positive passing environment"
    ]
  },
  "IND": {
    "team": "IND",
    "stadium": "Lucas Oil Stadium",
    "dome": true,
    "flags": [
      "DOME"
    ],
    "wind_mph": 0,
    "temp_f": 72,
    "precip_code": 0,
    "description": "Dome \u2014 no weather impact",
    "advisory": [
      "Dome \u2014 positive passing environment"
    ]
  },
  "JAX": {
    "team": "JAX",
    "stadium": "EverBank Stadium",
    "dome": false,
    "flags": [
      "PRECIP"
    ],
    "wind_mph": 11.7,
    "temp_f": 79.7,
    "precip_code": 51,
    "description": "rain/snow expected",
    "advisory": [
      "Rain/snow \u2014 upgrade RB, downgrade WR ceiling"
    ]
  },
  "KC": {
    "team": "KC",
    "stadium": "GEHA Field at Arrowhead",
    "dome": false,
    "flags": [
      "PRECIP"
    ],
    "wind_mph": 19.0,
    "temp_f": 72.4,
    "precip_code": 95,
    "description": "rain/snow expected",
    "advisory": [
      "Rain/snow \u2014 upgrade RB, downgrade WR ceiling"
    ]
  },
  "LAC": {
    "team": "LAC",
    "stadium": "SoFi Stadium",
    "dome": true,
    "flags": [
      "DOME"
    ],
    "wind_mph": 0,
    "temp_f": 72,
    "precip_code": 0,
    "description": "Dome \u2014 no weather impact",
    "advisory": [
      "Dome \u2014 positive passing environment"
    ]
  },
  "LAR": {
    "team": "LAR",
    "stadium": "SoFi Stadium",
    "dome": true,
    "flags": [
      "DOME"
    ],
    "wind_mph": 0,
    "temp_f": 72,
    "precip_code": 0,
    "description": "Dome \u2014 no weather impact",
    "advisory": [
      "Dome \u2014 positive passing environment"
    ]
  },
  "LV": {
    "team": "LV",
    "stadium": "Allegiant Stadium",
    "dome": true,
    "flags": [
      "DOME"
    ],
    "wind_mph": 0,
    "temp_f": 72,
    "precip_code": 0,
    "description": "Dome \u2014 no weather impact",
    "advisory": [
      "Dome \u2014 positive passing environment"
    ]
  },
  "MIA": {
    "team": "MIA",
    "stadium": "Hard Rock Stadium",
    "dome": false,
    "flags": [
      "PRECIP"
    ],
    "wind_mph": 15.9,
    "temp_f": 81.2,
    "precip_code": 51,
    "description": "rain/snow expected",
    "advisory": [
      "Rain/snow \u2014 upgrade RB, downgrade WR ceiling"
    ]
  },
  "MIN": {
    "team": "MIN",
    "stadium": "U.S. Bank Stadium",
    "dome": true,
    "flags": [
      "DOME"
    ],
    "wind_mph": 0,
    "temp_f": 72,
    "precip_code": 0,
    "description": "Dome \u2014 no weather impact",
    "advisory": [
      "Dome \u2014 positive passing environment"
    ]
  },
  "NE": {
    "team": "NE",
    "stadium": "Gillette Stadium",
    "dome": false,
    "flags": [
      "PRECIP"
    ],
    "wind_mph": 14.3,
    "temp_f": 59.6,
    "precip_code": 80,
    "description": "rain/snow expected",
    "advisory": [
      "Rain/snow \u2014 upgrade RB, downgrade WR ceiling"
    ]
  },
  "NO": {
    "team": "NO",
    "stadium": "Caesars Superdome",
    "dome": true,
    "flags": [
      "DOME"
    ],
    "wind_mph": 0,
    "temp_f": 72,
    "precip_code": 0,
    "description": "Dome \u2014 no weather impact",
    "advisory": [
      "Dome \u2014 positive passing environment"
    ]
  },
  "NYG": {
    "team": "NYG",
    "stadium": "MetLife Stadium",
    "dome": false,
    "flags": [
      "PRECIP"
    ],
    "wind_mph": 11.7,
    "temp_f": 72.5,
    "precip_code": 51,
    "description": "rain/snow expected",
    "advisory": [
      "Rain/snow \u2014 upgrade RB, downgrade WR ceiling"
    ]
  },
  "NYJ": {
    "team": "NYJ",
    "stadium": "MetLife Stadium",
    "dome": false,
    "flags": [
      "PRECIP"
    ],
    "wind_mph": 11.7,
    "temp_f": 72.5,
    "precip_code": 51,
    "description": "rain/snow expected",
    "advisory": [
      "Rain/snow \u2014 upgrade RB, downgrade WR ceiling"
    ]
  },
  "PHI": {
    "team": "PHI",
    "stadium": "Lincoln Financial Field",
    "dome": false,
    "flags": [
      "PRECIP"
    ],
    "wind_mph": 12.0,
    "temp_f": 71.7,
    "precip_code": 80,
    "description": "rain/snow expected",
    "advisory": [
      "Rain/snow \u2014 upgrade RB, downgrade WR ceiling"
    ]
  },
  "PIT": {
    "team": "PIT",
    "stadium": "Acrisure Stadium",
    "dome": false,
    "flags": [
      "PRECIP"
    ],
    "wind_mph": 13.0,
    "temp_f": 69.3,
    "precip_code": 65,
    "description": "rain/snow expected",
    "advisory": [
      "Rain/snow \u2014 upgrade RB, downgrade WR ceiling"
    ]
  },
  "SEA": {
    "team": "SEA",
    "stadium": "Lumen Field",
    "dome": false,
    "flags": [
      "CLEAR"
    ],
    "wind_mph": 8.5,
    "temp_f": 58.8,
    "precip_code": 3,
    "description": "59\u00b0F, clear",
    "advisory": []
  },
  "SF": {
    "team": "SF",
    "stadium": "Levi's Stadium",
    "dome": false,
    "flags": [
      "CLEAR"
    ],
    "wind_mph": 13.3,
    "temp_f": 64.5,
    "precip_code": 3,
    "description": "64\u00b0F, clear",
    "advisory": []
  },
  "TB": {
    "team": "TB",
    "stadium": "Raymond James Stadium",
    "dome": false,
    "flags": [
      "PRECIP"
    ],
    "wind_mph": 12.7,
    "temp_f": 76.8,
    "precip_code": 95,
    "description": "rain/snow expected",
    "advisory": [
      "Rain/snow \u2014 upgrade RB, downgrade WR ceiling"
    ]
  },
  "TEN": {
    "team": "TEN",
    "stadium": "Nissan Stadium",
    "dome": false,
    "flags": [
      "PRECIP"
    ],
    "wind_mph": 15.2,
    "temp_f": 76.2,
    "precip_code": 80,
    "description": "rain/snow expected",
    "advisory": [
      "Rain/snow \u2014 upgrade RB, downgrade WR ceiling"
    ]
  },
  "WSH": {
    "team": "WSH",
    "stadium": "Northwest Stadium",
    "dome": false,
    "flags": [
      "PRECIP"
    ],
    "wind_mph": 11.2,
    "temp_f": 69.4,
    "precip_code": 95,
    "description": "rain/snow expected",
    "advisory": [
      "Rain/snow \u2014 upgrade RB, downgrade WR ceiling"
    ]
  },
  "BAL": {
    "team": "BAL",
    "stadium": "M&T Bank Stadium",
    "dome": false,
    "flags": [
      "PRECIP"
    ],
    "wind_mph": 11.0,
    "temp_f": 72.1,
    "precip_code": 53,
    "description": "rain/snow expected",
    "advisory": [
      "Rain/snow \u2014 upgrade RB, downgrade WR ceiling"
    ]
  }
};

/**
 * Get weather flags for a player's NFL team.
 * Returns array of flag strings: ["WIND"], ["PRECIP"], ["COLD"], ["DOME"], ["CLEAR"]
 * Returns ["UNKNOWN"] if weather data unavailable — treat as non-blocking.
 *
 * @param {string} nflTeam - NFL team abbreviation (e.g. "KC", "BUF")
 * @returns {string[]}
 */
export function getWeatherFlags(nflTeam) {
  return WEATHER_DATA[nflTeam]?.flags ?? ["UNKNOWN"];
}

/**
 * Get advisory text for a player's matchup weather.
 * Returns array of advisory strings for display on player cards.
 *
 * @param {string} nflTeam
 * @returns {string[]}
 */
export function getWeatherAdvisory(nflTeam) {
  return WEATHER_DATA[nflTeam]?.advisory ?? [];
}

/**
 * True if a team's game has any meaningful weather flag (not DOME/CLEAR/UNKNOWN).
 * Used to show/hide the weather indicator on player cards.
 *
 * @param {string} nflTeam
 * @returns {boolean}
 */
export function hasWeatherImpact(nflTeam) {
  const flags = getWeatherFlags(nflTeam);
  return flags.some(f => ["WIND", "PRECIP", "COLD"].includes(f));
}

export const WEATHER_FETCHED_AT = "2026-09-09T10:11:37.450204+00:00";
