// weather_data.js — Gridiron Oracle game-day weather
// AUTO-GENERATED by scripts/fetch_weather.py — DO NOT EDIT MANUALLY
// Fetched: 2026-03-22T06:16:18.093221+00:00
// Flagged games: BUF, CHI, CIN, CLE, GB, JAX, KC, NE, NYG, NYJ, PHI, PIT, SEA, TB, WSH, BAL

export const WEATHER_DATA = {
  "ARI": {
    "team": "ARI",
    "stadium": "State Farm Stadium",
    "dome": true,
    "flags": [
      "DOME"
    ],
    "wind_mph": 0,
    "temp_f": 72,
    "precip_code": 0,
    "description": "Dome \u2014 no weather impact",
    "advisory": [
      "Dome \u2014 positive passing environment"
    ]
  },
  "ATL": {
    "team": "ATL",
    "stadium": "Mercedes-Benz Stadium",
    "dome": true,
    "flags": [
      "DOME"
    ],
    "wind_mph": 0,
    "temp_f": 72,
    "precip_code": 0,
    "description": "Dome \u2014 no weather impact",
    "advisory": [
      "Dome \u2014 positive passing environment"
    ]
  },
  "BUF": {
    "team": "BUF",
    "stadium": "Highmark Stadium",
    "dome": false,
    "flags": [
      "WIND",
      "PRECIP",
      "COLD"
    ],
    "wind_mph": 23.3,
    "temp_f": 23.9,
    "precip_code": 73,
    "description": "wind 23 mph, rain/snow expected, 24\u00b0F",
    "advisory": [
      "Wind >20 mph \u2014 downgrade WR/TE passing game",
      "Rain/snow \u2014 upgrade RB, downgrade WR ceiling",
      "Cold (<25\u00b0F) \u2014 mild passing efficiency reduction"
    ]
  },
  "CAR": {
    "team": "CAR",
    "stadium": "Bank of America Stadium",
    "dome": false,
    "flags": [
      "CLEAR"
    ],
    "wind_mph": 16.3,
    "temp_f": 48.6,
    "precip_code": 3,
    "description": "49\u00b0F, clear",
    "advisory": []
  },
  "CHI": {
    "team": "CHI",
    "stadium": "Soldier Field",
    "dome": false,
    "flags": [
      "WIND",
      "PRECIP"
    ],
    "wind_mph": 24.0,
    "temp_f": 33.0,
    "precip_code": 51,
    "description": "wind 24 mph, rain/snow expected",
    "advisory": [
      "Wind >20 mph \u2014 downgrade WR/TE passing game",
      "Rain/snow \u2014 upgrade RB, downgrade WR ceiling"
    ]
  },
  "CIN": {
    "team": "CIN",
    "stadium": "Paycor Stadium",
    "dome": false,
    "flags": [
      "PRECIP"
    ],
    "wind_mph": 17.9,
    "temp_f": 34.9,
    "precip_code": 71,
    "description": "rain/snow expected",
    "advisory": [
      "Rain/snow \u2014 upgrade RB, downgrade WR ceiling"
    ]
  },
  "CLE": {
    "team": "CLE",
    "stadium": "Huntington Bank Field",
    "dome": false,
    "flags": [
      "PRECIP"
    ],
    "wind_mph": 18.8,
    "temp_f": 28.7,
    "precip_code": 55,
    "description": "rain/snow expected",
    "advisory": [
      "Rain/snow \u2014 upgrade RB, downgrade WR ceiling"
    ]
  },
  "DAL": {
    "team": "DAL",
    "stadium": "AT&T Stadium",
    "dome": true,
    "flags": [
      "DOME"
    ],
    "wind_mph": 0,
    "temp_f": 72,
    "precip_code": 0,
    "description": "Dome \u2014 no weather impact",
    "advisory": [
      "Dome \u2014 positive passing environment"
    ]
  },
  "DEN": {
    "team": "DEN",
    "stadium": "Empower Field",
    "dome": false,
    "flags": [
      "CLEAR"
    ],
    "wind_mph": 12.6,
    "temp_f": 54.3,
    "precip_code": 3,
    "description": "54\u00b0F, clear",
    "advisory": []
  },
  "DET": {
    "team": "DET",
    "stadium": "Ford Field",
    "dome": true,
    "flags": [
      "DOME"
    ],
    "wind_mph": 0,
    "temp_f": 72,
    "precip_code": 0,
    "description": "Dome \u2014 no weather impact",
    "advisory": [
      "Dome \u2014 positive passing environment"
    ]
  },
  "GB": {
    "team": "GB",
    "stadium": "Lambeau Field",
    "dome": false,
    "flags": [
      "WIND",
      "PRECIP"
    ],
    "wind_mph": 21.8,
    "temp_f": 26.8,
    "precip_code": 53,
    "description": "wind 22 mph, rain/snow expected",
    "advisory": [
      "Wind >20 mph \u2014 downgrade WR/TE passing game",
      "Rain/snow \u2014 upgrade RB, downgrade WR ceiling"
    ]
  },
  "HOU": {
    "team": "HOU",
    "stadium": "NRG Stadium",
    "dome": true,
    "flags": [
      "DOME"
    ],
    "wind_mph": 0,
    "temp_f": 72,
    "precip_code": 0,
    "description": "Dome \u2014 no weather impact",
    "advisory": [
      "Dome \u2014 positive passing environment"
    ]
  },
  "IND": {
    "team": "IND",
    "stadium": "Lucas Oil Stadium",
    "dome": true,
    "flags": [
      "DOME"
    ],
    "wind_mph": 0,
    "temp_f": 72,
    "precip_code": 0,
    "description": "Dome \u2014 no weather impact",
    "advisory": [
      "Dome \u2014 positive passing environment"
    ]
  },
  "JAX": {
    "team": "JAX",
    "stadium": "EverBank Stadium",
    "dome": false,
    "flags": [
      "PRECIP"
    ],
    "wind_mph": 18.8,
    "temp_f": 56.9,
    "precip_code": 51,
    "description": "rain/snow expected",
    "advisory": [
      "Rain/snow \u2014 upgrade RB, downgrade WR ceiling"
    ]
  },
  "KC": {
    "team": "KC",
    "stadium": "GEHA Field at Arrowhead",
    "dome": false,
    "flags": [
      "WIND"
    ],
    "wind_mph": 23.5,
    "temp_f": 38.9,
    "precip_code": 3,
    "description": "wind 24 mph",
    "advisory": [
      "Wind >20 mph \u2014 downgrade WR/TE passing game"
    ]
  },
  "LAC": {
    "team": "LAC",
    "stadium": "SoFi Stadium",
    "dome": true,
    "flags": [
      "DOME"
    ],
    "wind_mph": 0,
    "temp_f": 72,
    "precip_code": 0,
    "description": "Dome \u2014 no weather impact",
    "advisory": [
      "Dome \u2014 positive passing environment"
    ]
  },
  "LAR": {
    "team": "LAR",
    "stadium": "SoFi Stadium",
    "dome": true,
    "flags": [
      "DOME"
    ],
    "wind_mph": 0,
    "temp_f": 72,
    "precip_code": 0,
    "description": "Dome \u2014 no weather impact",
    "advisory": [
      "Dome \u2014 positive passing environment"
    ]
  },
  "LV": {
    "team": "LV",
    "stadium": "Allegiant Stadium",
    "dome": true,
    "flags": [
      "DOME"
    ],
    "wind_mph": 0,
    "temp_f": 72,
    "precip_code": 0,
    "description": "Dome \u2014 no weather impact",
    "advisory": [
      "Dome \u2014 positive passing environment"
    ]
  },
  "MIA": {
    "team": "MIA",
    "stadium": "Hard Rock Stadium",
    "dome": false,
    "flags": [
      "CLEAR"
    ],
    "wind_mph": 15.2,
    "temp_f": 72.0,
    "precip_code": 3,
    "description": "72\u00b0F, clear",
    "advisory": []
  },
  "MIN": {
    "team": "MIN",
    "stadium": "U.S. Bank Stadium",
    "dome": true,
    "flags": [
      "DOME"
    ],
    "wind_mph": 0,
    "temp_f": 72,
    "precip_code": 0,
    "description": "Dome \u2014 no weather impact",
    "advisory": [
      "Dome \u2014 positive passing environment"
    ]
  },
  "NE": {
    "team": "NE",
    "stadium": "Gillette Stadium",
    "dome": false,
    "flags": [
      "PRECIP"
    ],
    "wind_mph": 15.1,
    "temp_f": 29.1,
    "precip_code": 71,
    "description": "rain/snow expected",
    "advisory": [
      "Rain/snow \u2014 upgrade RB, downgrade WR ceiling"
    ]
  },
  "NO": {
    "team": "NO",
    "stadium": "Caesars Superdome",
    "dome": true,
    "flags": [
      "DOME"
    ],
    "wind_mph": 0,
    "temp_f": 72,
    "precip_code": 0,
    "description": "Dome \u2014 no weather impact",
    "advisory": [
      "Dome \u2014 positive passing environment"
    ]
  },
  "NYG": {
    "team": "NYG",
    "stadium": "MetLife Stadium",
    "dome": false,
    "flags": [
      "PRECIP"
    ],
    "wind_mph": 16.6,
    "temp_f": 34.7,
    "precip_code": 71,
    "description": "rain/snow expected",
    "advisory": [
      "Rain/snow \u2014 upgrade RB, downgrade WR ceiling"
    ]
  },
  "NYJ": {
    "team": "NYJ",
    "stadium": "MetLife Stadium",
    "dome": false,
    "flags": [
      "PRECIP"
    ],
    "wind_mph": 16.6,
    "temp_f": 34.7,
    "precip_code": 71,
    "description": "rain/snow expected",
    "advisory": [
      "Rain/snow \u2014 upgrade RB, downgrade WR ceiling"
    ]
  },
  "PHI": {
    "team": "PHI",
    "stadium": "Lincoln Financial Field",
    "dome": false,
    "flags": [
      "PRECIP"
    ],
    "wind_mph": 16.5,
    "temp_f": 37.0,
    "precip_code": 51,
    "description": "rain/snow expected",
    "advisory": [
      "Rain/snow \u2014 upgrade RB, downgrade WR ceiling"
    ]
  },
  "PIT": {
    "team": "PIT",
    "stadium": "Acrisure Stadium",
    "dome": false,
    "flags": [
      "PRECIP"
    ],
    "wind_mph": 19.1,
    "temp_f": 31.8,
    "precip_code": 51,
    "description": "rain/snow expected",
    "advisory": [
      "Rain/snow \u2014 upgrade RB, downgrade WR ceiling"
    ]
  },
  "SEA": {
    "team": "SEA",
    "stadium": "Lumen Field",
    "dome": false,
    "flags": [
      "PRECIP"
    ],
    "wind_mph": 16.1,
    "temp_f": 39.9,
    "precip_code": 63,
    "description": "rain/snow expected",
    "advisory": [
      "Rain/snow \u2014 upgrade RB, downgrade WR ceiling"
    ]
  },
  "SF": {
    "team": "SF",
    "stadium": "Levi's Stadium",
    "dome": false,
    "flags": [
      "CLEAR"
    ],
    "wind_mph": 13.2,
    "temp_f": 61.0,
    "precip_code": 3,
    "description": "61\u00b0F, clear",
    "advisory": []
  },
  "TB": {
    "team": "TB",
    "stadium": "Raymond James Stadium",
    "dome": false,
    "flags": [
      "WIND",
      "PRECIP"
    ],
    "wind_mph": 20.9,
    "temp_f": 66.0,
    "precip_code": 51,
    "description": "wind 21 mph, rain/snow expected",
    "advisory": [
      "Wind >20 mph \u2014 downgrade WR/TE passing game",
      "Rain/snow \u2014 upgrade RB, downgrade WR ceiling"
    ]
  },
  "TEN": {
    "team": "TEN",
    "stadium": "Nissan Stadium",
    "dome": false,
    "flags": [
      "CLEAR"
    ],
    "wind_mph": 15.2,
    "temp_f": 39.3,
    "precip_code": 3,
    "description": "39\u00b0F, clear",
    "advisory": []
  },
  "WSH": {
    "team": "WSH",
    "stadium": "Northwest Stadium",
    "dome": false,
    "flags": [
      "PRECIP"
    ],
    "wind_mph": 18.8,
    "temp_f": 38.2,
    "precip_code": 51,
    "description": "rain/snow expected",
    "advisory": [
      "Rain/snow \u2014 upgrade RB, downgrade WR ceiling"
    ]
  },
  "BAL": {
    "team": "BAL",
    "stadium": "M&T Bank Stadium",
    "dome": false,
    "flags": [
      "PRECIP"
    ],
    "wind_mph": 18.4,
    "temp_f": 38.1,
    "precip_code": 51,
    "description": "rain/snow expected",
    "advisory": [
      "Rain/snow \u2014 upgrade RB, downgrade WR ceiling"
    ]
  }
};

/**
 * Get weather flags for a player's NFL team.
 * Returns array of flag strings: ["WIND"], ["PRECIP"], ["COLD"], ["DOME"], ["CLEAR"]
 * Returns ["UNKNOWN"] if weather data unavailable — treat as non-blocking.
 *
 * @param {string} nflTeam - NFL team abbreviation (e.g. "KC", "BUF")
 * @returns {string[]}
 */
export function getWeatherFlags(nflTeam) {
  return WEATHER_DATA[nflTeam]?.flags ?? ["UNKNOWN"];
}

/**
 * Get advisory text for a player's matchup weather.
 * Returns array of advisory strings for display on player cards.
 *
 * @param {string} nflTeam
 * @returns {string[]}
 */
export function getWeatherAdvisory(nflTeam) {
  return WEATHER_DATA[nflTeam]?.advisory ?? [];
}

/**
 * True if a team's game has any meaningful weather flag (not DOME/CLEAR/UNKNOWN).
 * Used to show/hide the weather indicator on player cards.
 *
 * @param {string} nflTeam
 * @returns {boolean}
 */
export function hasWeatherImpact(nflTeam) {
  const flags = getWeatherFlags(nflTeam);
  return flags.some(f => ["WIND", "PRECIP", "COLD"].includes(f));
}

export const WEATHER_FETCHED_AT = "2026-03-22T06:16:18.093221+00:00";
