#!/usr/bin/env python3
"""
fetch_draft_picks.py — Gridiron Oracle Rookie Baseline Builder
=================================================================
Pulls historical draft-slot-to-rookie-fantasy-output data via nflreadpy,
used to give rookies (no nfl_data.js history) a real, data-grounded
projection on Draft Board instead of a blank "no model data" row.

Builds round-by-position average/median rookie-season PPR points from
the last 10 completed seasons, plus the current draft class's actual
round/pick for lookup.

Output: src/utils/draft_picks.js

Usage:
  python3 scripts/fetch_draft_picks.py
"""
import json
import logging
import sys
from datetime import datetime, timezone
from pathlib import Path

import nflreadpy as nfl
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = ROOT / "src" / "utils" / "draft_picks.js"

BASELINE_START_SEASON = 2015
BASELINE_END_SEASON = 2025   # last fully-completed season
CURRENT_DRAFT_CLASS_SEASON = 2026  # most recent draft class relevant to a 2026 draft

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)],
)
log = logging.getLogger(__name__)

POSITIONS = ["QB", "RB", "WR", "TE"]


def build_round_baselines() -> dict:
    log.info(f"Building round-by-position rookie baselines ({BASELINE_START_SEASON}-{BASELINE_END_SEASON})...")

    picks = nfl.load_draft_picks().to_pandas()
    picks = picks[
        (picks["season"] >= BASELINE_START_SEASON) &
        (picks["season"] <= BASELINE_END_SEASON) &
        (picks["position"].isin(POSITIONS))
    ][["gsis_id", "season", "round", "position"]]

    all_rookie_pts = []
    for yr in range(BASELINE_START_SEASON, BASELINE_END_SEASON + 1):
        yr_picks = picks[picks["season"] == yr]
        if yr_picks.empty:
            continue
        stats = nfl.load_player_stats([yr]).to_pandas()
        # Per-game average, not season total — must match nfl_data.js's
        # season_avg_pts, which is a per-game mean, not a season sum.
        # Using a season total here previously produced VORP values in
        # the hundreds, which dominated the Model $ allocation for every
        # other player on the board.
        rookie_pts = (
            stats.groupby("player_id")["fantasy_points_ppr"]
            .mean()
            .reset_index()
        )
        rookie_pts.columns = ["gsis_id", "rookie_avg_pts"]
        merged = yr_picks.merge(rookie_pts, on="gsis_id", how="left")
        merged["rookie_avg_pts"] = merged["rookie_avg_pts"].fillna(0.0)
        all_rookie_pts.append(merged)

    full = pd.concat(all_rookie_pts)

    baselines = {}
    for pos in POSITIONS:
        pos_df = full[full["position"] == pos]
        baselines[pos] = {}
        for rnd in sorted(pos_df["round"].unique()):
            rnd_df = pos_df[pos_df["round"] == rnd]
            baselines[pos][int(rnd)] = {
                "mean": round(float(rnd_df["rookie_avg_pts"].mean()), 1),
                "median": round(float(rnd_df["rookie_avg_pts"].median()), 1),
                "count": int(len(rnd_df)),
            }

    log.info(f"Baselines built for {len(POSITIONS)} positions")
    return baselines


def fetch_current_class() -> dict:
    """
    { gsis_id: { round, pick, position, name } } for the most recent
    draft class — used to look up a specific rookie's slot.
    """
    log.info(f"Fetching {CURRENT_DRAFT_CLASS_SEASON} draft class...")
    picks = nfl.load_draft_picks().to_pandas()
    recent = picks[
        (picks["season"] == CURRENT_DRAFT_CLASS_SEASON) &
        (picks["position"].isin(POSITIONS))
    ]

    result = {}
    for _, row in recent.iterrows():
        gsis = row.get("gsis_id")
        if not gsis or pd.isna(gsis):
            continue
        result[str(gsis)] = {
            "round": int(row["round"]),
            "pick": int(row["pick"]),
            "position": row["position"],
            "name": row.get("pfr_player_name", "Unknown"),
        }

    log.info(f"{len(result)} rookies mapped for {CURRENT_DRAFT_CLASS_SEASON} class")
    return result


def write_output(baselines: dict, current_class: dict):
    timestamp = datetime.now(timezone.utc).isoformat()

    js_content = f"""// draft_picks.js — Gridiron Oracle rookie baseline data
// AUTO-GENERATED by scripts/fetch_draft_picks.py — DO NOT EDIT MANUALLY
// Baseline seasons: {BASELINE_START_SEASON}-{BASELINE_END_SEASON}
// Current draft class: {CURRENT_DRAFT_CLASS_SEASON}
// Generated: {timestamp}
//
// ROUND_BASELINES: historical average rookie-season PPR points by
// position and round, used to project rookies with no nfl_data.js
// history. Built from real outcomes, not assumptions — but note this
// is a rough baseline, not a player-specific projection. A "good"
// or "bad" rookie within the same draft slot will vary widely; this
// gives a reasonable starting point rather than pretending precision.

export const ROUND_BASELINES = {json.dumps(baselines, indent=2)};

// CURRENT_DRAFT_CLASS: gsis_id -> round, pick, position, name
export const CURRENT_DRAFT_CLASS = {json.dumps(current_class, indent=2)};

export const DRAFT_PICKS_META = {{
  baseline_start: {BASELINE_START_SEASON},
  baseline_end: {BASELINE_END_SEASON},
  current_class_season: {CURRENT_DRAFT_CLASS_SEASON},
  generated_at: "{timestamp}",
}};
"""
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(js_content, encoding="utf-8")
    log.info(f"Wrote baselines + {len(current_class)} rookies to {OUTPUT_PATH}")


def main():
    baselines = build_round_baselines()
    current_class = fetch_current_class()
    write_output(baselines, current_class)
    log.info("=== Draft picks fetch complete ===")


if __name__ == "__main__":
    main()