#!/usr/bin/env python3
"""
fetch_adp.py — Gridiron Oracle
Pulls current-season ADP (Average Draft Position) data from the
Fantasy Football Calculator public REST API (free, no key required).
Matches your league's scoring: 12-team, full PPR.

Output: src/utils/adp_data.js
"""

import json
import logging
import re
import sys
from pathlib import Path
from datetime import datetime, timezone

import requests

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger(__name__)

FFC_URL = "https://fantasyfootballcalculator.com/api/v1/adp/ppr"
SEASON = 2026
TEAMS = 12
OUTPUT_PATH = Path(__file__).resolve().parent.parent / "src" / "utils" / "adp_data.js"

# Suffixes stripped during name normalization for matching against nfl_data.js
SUFFIXES = {"jr", "sr", "ii", "iii", "iv", "v"}


def normalize_name(name: str) -> str:
    """
    Normalize a player name for cross-source matching.
    Lowercase, strip punctuation, strip generational suffixes.
    Mirrors the caution in spec §4.2 re: name-string joins — this is a
    best-effort fallback since FFC has no GSIS/ESPN ID to join on directly.
    """
    if not name:
        return ""
    n = name.lower()
    n = re.sub(r"[.'\-]", "", n)          # strip periods, apostrophes, hyphens
    n = re.sub(r"\s+", " ", n).strip()
    parts = [p for p in n.split(" ") if p not in SUFFIXES]
    return " ".join(parts)


def fetch_adp():
    log.info("=== Gridiron Oracle — ADP fetch ===")
    log.info(f"Fetching PPR ADP ({TEAMS}-team, {SEASON}) from Fantasy Football Calculator...")

    params = {"teams": TEAMS, "year": SEASON, "position": "all"}
    try:
        resp = requests.get(FFC_URL, params=params, timeout=15)
        resp.raise_for_status()
    except requests.RequestException as e:
        log.error(f"ADP fetch failed: {e}")
        sys.exit(1)

    data = resp.json()
    players = data.get("players", [])

    if not players:
        log.error("ADP fetch returned zero players — aborting, file NOT written")
        sys.exit(1)

    log.info(f"  {len(players)} players returned")
    return players


def build_records(players):
    records = []
    skipped = 0

    for p in players:
        name = p.get("name")
        if not name:
            skipped += 1
            continue

        records.append({
            "player_id": p.get("player_id"),      # FFC's own stable ID
            "name": name,
            "normalized_name": normalize_name(name),
            "position": p.get("position", "UNK"),
            "team": p.get("team", "UNK"),
            "bye": p.get("bye"),
            "adp": p.get("adp"),                   # overall ADP, decimal (e.g. 1.7)
            "adp_formatted": p.get("adp_formatted"),  # "round.pick" display string (e.g. "1.02")
            "adp_std_dev": p.get("stdev"),
            "adp_high": p.get("high"),             # best (earliest) overall pick, integer
            "adp_low": p.get("low"),               # worst (latest) overall pick, integer
            "times_drafted": p.get("times_drafted"),
        })

    if skipped:
        log.warning(f"  Skipped {skipped} entries with no name field")

    return records


def write_output(records):
    by_name = {r["normalized_name"]: r for r in records if r["normalized_name"]}

    duplicate_check = {}
    dupes = 0
    for r in records:
        key = r["normalized_name"]
        if key in duplicate_check:
            dupes += 1
        duplicate_check[key] = True
    if dupes:
        log.warning(f"  {dupes} normalized-name collisions — last entry wins in ADP_BY_NAME")

    js_content = f"""// adp_data.js — AUTO-GENERATED by scripts/fetch_adp.py
// Source: Fantasy Football Calculator (fantasyfootballcalculator.com), free public API
// League match: {TEAMS}-team, full PPR
// Fetched: {datetime.now(timezone.utc).isoformat()}
// DO NOT EDIT BY HAND

export const ADP_LIST = {json.dumps(records, indent=2)};

// Lookup by normalized name (lowercase, no punctuation, suffixes stripped)
// Caution: name-based join, not ID-based — verify before trusting an exact
// match on players with common names. Per spec §4.2 join-by-ID guidance,
// this is a best-effort fallback since FFC has no GSIS/ESPN cross-reference.
export const ADP_BY_NAME = {json.dumps(by_name, indent=2)};

export const ADP_META = {{
  source: "fantasyfootballcalculator.com",
  scoring: "ppr",
  teams: {TEAMS},
  season: {SEASON},
  fetched_at: "{datetime.now(timezone.utc).isoformat()}",
  player_count: {len(records)},
}};
"""

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(js_content)
    log.info(f"Written: {len(records)} players → {OUTPUT_PATH.relative_to(Path.cwd())}")


def main():
    players = fetch_adp()
    records = build_records(players)
    write_output(records)
    log.info("=== ADP fetch complete ===")


if __name__ == "__main__":
    main()